// This file was auto-generated by Fern from our API Definition.

import type * as VideoGenApi from "../../../../index.js";

/**
 * @example
 *     {
 *         url: "https://webhooks.myapp.com/videogen",
 *         events: ["tool_execution.succeeded", "tool_execution.failed"]
 *     }
 */
export interface CreateWebhookEndpointRequest {
    /** HTTPS URL that will receive webhook POST requests. */
    url: string;
    description?: string | null;
    events: VideoGenApi.WebhookEventName[];
}
