// This file was auto-generated by Fern from our API Definition.

import type * as VideogenApi from "../../../../index.js";

/**
 * @example
 *     {
 *         url: "url",
 *         events: ["tool_execution.succeeded"]
 *     }
 */
export interface CreateWebhookEndpointRequest {
    /** HTTPS URL that will receive webhook POST requests. */
    url: string;
    description?: string | null;
    events: VideogenApi.ToolExecutionWebhookEventName[];
}
