// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         endpointId: "ep_28KVX7vT9mQ2sL4nR6pB1cD0fG"
 *     }
 */
export interface DeleteWebhookEndpointRequest {
    /** The webhook endpoint id (e.g. `ep_...`) returned by `POST /v1/webhooks/endpoints`. */
    endpointId: string;
}
