// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         endpointId: "endpointId"
 *     }
 */
export interface DeleteWebhookEndpointRequest {
    /** The webhook endpoint id returned by `POST /v1/webhooks/endpoints`. */
    endpointId: string;
}
