// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         entityId: "entityId",
 *         fileId: "fileId"
 *     }
 */
export interface AddEntityReferenceRequest {
    /** The entity id (e.g. `vg_enti_...`). */
    entityId: string;
    /** The file id (e.g. `vg_file_...`) of an image to attach as a reference. */
    fileId: string;
    /** Optional description of the reference. */
    description?: string;
    /** When true, make this the entity's primary reference (used for its thumbnail). */
    isDefault?: boolean;
}
