// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         entityType: "ACTOR",
 *         name: "name"
 *     }
 */
export interface CreateEntityRequest {
    /** ACTOR features a consistent character; VISUAL_STYLE guides the look of generated images. */
    entityType: CreateEntityRequest.EntityType;
    /** Display name. */
    name: string;
    /** Optional description. */
    description?: string;
}

export namespace CreateEntityRequest {
    /** ACTOR features a consistent character; VISUAL_STYLE guides the look of generated images. */
    export const EntityType = {
        Actor: "ACTOR",
        VisualStyle: "VISUAL_STYLE",
    } as const;
    export type EntityType = (typeof EntityType)[keyof typeof EntityType];
}
