// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         entityType: "VISUAL_STYLE",
 *         name: "Pastel watercolor",
 *         description: "Soft pastel watercolor look for lifestyle clips."
 *     }
 */
export interface CreateEntityRequest {
    /** ACTOR features a consistent character; PRODUCT features a consistent product or object; VISUAL_STYLE guides the look of generated images. */
    entityType: CreateEntityRequest.EntityType;
    /** Display name. */
    name: string;
    /** Optional description. */
    description?: string;
}

export namespace CreateEntityRequest {
    /** ACTOR features a consistent character; PRODUCT features a consistent product or object; VISUAL_STYLE guides the look of generated images. */
    export const EntityType = {
        Actor: "ACTOR",
        Product: "PRODUCT",
        VisualStyle: "VISUAL_STYLE",
    } as const;
    export type EntityType = (typeof EntityType)[keyof typeof EntityType];
}
