// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         entityId: "vg_enti_a1b2c3d4e5f6"
 *     }
 */
export interface GetEntityRequest {
    /** The entity id (e.g. `vg_enti_...`). */
    entityId: string;
}
