// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         entityId: "vg_enti_a1b2c3d4e5f6",
 *         fileId: "vg_file_mot8bV5POiscDeHyo7TF1g"
 *     }
 */
export interface RemoveEntityReferenceRequest {
    /** The entity id (e.g. `vg_enti_...`). */
    entityId: string;
    /** The file id (e.g. `vg_file_...`) of the reference to remove. */
    fileId: string;
}
