// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         entityId: "entityId",
 *         fileId: "fileId"
 *     }
 */
export interface RemoveEntityReferenceRequest {
    /** The entity id (e.g. `vg_enti_...`). */
    entityId: string;
    /** The file id (e.g. `vg_file_...`) of the reference to remove. */
    fileId: string;
}
