// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         entityId: "vg_enti_a1b2c3d4e5f6",
 *         name: "Maya the presenter",
 *         description: "Friendly on-camera host for product explainers and demos."
 *     }
 */
export interface UpdateEntityRequest {
    /** The entity id (e.g. `vg_enti_...`). */
    entityId: string;
    /** New display name. Omit to leave unchanged. */
    name?: string | null;
    /** New description. Omit to leave unchanged. */
    description?: string | null;
}
