// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         entityId: "entityId"
 *     }
 */
export interface UpdateEntityRequest {
    /** The entity id (e.g. `vg_enti_...`). */
    entityId: string;
    /** New display name. Omit to leave unchanged. */
    name?: string | null;
    /** New description. Omit to leave unchanged. */
    description?: string | null;
}
