// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         apiTaskExecutionId: "apiTaskExecutionId"
 *     }
 */
export interface CancelToolExecutionRequest {
    /** Execution id from a `POST /v1/tools/...` response */
    apiTaskExecutionId: string;
}
