// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         executionId: "executionId"
 *     }
 */
export interface CancelToolExecutionRequest {
    executionId: string;
}
