// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         toolExecutionId: "vg_tool_ccm3abc123defcm3xyz789ghi"
 *     }
 */
export interface CancelToolExecutionRequest {
    /** The tool execution id returned when the tool was started. */
    toolExecutionId: string;
}
