// This file was auto-generated by Fern from our API Definition.

import type * as VideoGenApi from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface GenerateVideoClipRequest {
    /** Text prompt describing the video to generate. Optional when reference images or a video are provided. */
    prompt?: string;
    /** Optional file ids of reference images (e.g. `["vg_file_..."]`). Upload files first via `POST /v1/files/upload`, then pass the returned ids here. When provided, the model animates or uses these images as guidance. */
    imageFileIds?: string[];
    /** Optional file id of a source video (e.g. `vg_file_...`). Upload a file first via `POST /v1/files/upload`, then pass the returned id here. When provided, the model restyles or transforms the input video. */
    videoFileId?: string;
    /** When true, the generated video is guaranteed to include audio. When false, audio may still be present. Defaults to false. */
    generateAudio?: boolean;
    /** Aspect ratio for the generated video. Defaults to 16:9 when omitted. */
    aspectRatio?: VideoGenApi.AspectRatio;
    watermarkMode?: VideoGenApi.WatermarkMode;
    /** Number of output results to generate. Defaults to 1. */
    numResults?: number;
    /** When true, generated files are temporary. Temporary files are guaranteed to be available for 24 hours, after which they may be archived at any time. Temporary files are not analyzed (no description, transcript, or embedding will be generated), so they will not appear in search results. Defaults to false. */
    isOutputTemporary?: boolean;
}
