// This file was auto-generated by Fern from our API Definition.

import type * as VideoGenApi from "../../../../index.js";

/**
 * @example
 *     {
 *         quality: "STANDARD"
 *     }
 */
export interface GenerateVideoClipRequest {
    /** Text prompt describing the video to generate. Optional when reference media is provided. Describe the video in plain language; any reference media you provide is incorporated automatically. */
    prompt?: string;
    /** Optional file ids of reference images (e.g. `["vg_file_..."]`). Upload files first via `POST /v1/files/upload`, then pass the returned ids here. When provided, the images are animated or used as visual guidance for the generated video. */
    imageFileIds?: string[];
    /** Optional file ids of reference videos (e.g. `["vg_file_..."]`). Upload files first via `POST /v1/files/upload`, then pass the returned ids here. They are used as motion or style guidance for the generated video. */
    videoFileIds?: string[];
    /** Optional file ids of reference audio clips (e.g. `["vg_file_..."]`) used for native lip-sync and soundtrack. Upload files first via `POST /v1/files/upload`, then pass the returned ids here. */
    audioFileIds?: string[];
    /** When true, the generated video is guaranteed to include audio. When false, audio may still be present. Defaults to false. */
    generateAudio?: boolean;
    /** Desired clip length in seconds. A whole number between 1 and 15. Defaults to 6 when omitted. This endpoint produces a single short clip. For longer, multi-scene, professionally edited videos, use a video workflow such as `POST /v1/workflows/script-to-video`. */
    durationSeconds?: number | null;
    /** Aspect ratio for the generated video. Defaults to 16:9 when omitted. */
    aspectRatio?: VideoGenApi.AspectRatio;
    /** Video generation quality tier. STANDARD is fastest; HIGH is slowest and highest quality. */
    quality: GenerateVideoClipRequest.Quality;
    watermarkMode?: VideoGenApi.WatermarkMode;
    /** Number of output results to generate. Defaults to 1. */
    numResults?: number;
    /** When true, generated files are temporary. Temporary files are guaranteed to be available for 24 hours, after which they may be archived at any time. Temporary files are not analyzed (no description, transcript, or embedding will be generated), so they will not appear in search results. Defaults to false. */
    isOutputTemporary?: boolean;
}

export namespace GenerateVideoClipRequest {
    /** Video generation quality tier. STANDARD is fastest; HIGH is slowest and highest quality. */
    export const Quality = {
        Standard: "STANDARD",
        High: "HIGH",
    } as const;
    export type Quality = (typeof Quality)[keyof typeof Quality];
}
