// This file was auto-generated by Fern from our API Definition.

import type * as VideogenApi from "../../../../index.js";

/**
 * @example
 *     {
 *         avatarPresenterId: "avatarPresenterId",
 *         audio: {
 *             storageFileId: "storageFileId",
 *             type: "IMAGE"
 *         }
 *     }
 */
export interface GenerateAvatarRequest {
    /** Presenter id from `GET /v1/resources/avatar-presenters`. */
    avatarPresenterId: string;
    /** Reference to an `AUDIO` file, typically from a prior text-to-speech result. */
    audio: VideogenApi.StorageFileRef;
    /** Number of output candidates to generate. Defaults to 1. */
    numCandidates?: number;
    /** When true, generated files are scoped as temporary. Defaults to false. */
    isOutputTemporary?: boolean;
}
