// This file was auto-generated by Fern from our API Definition.

import type * as VideogenApi from "../../../../index.js";

/**
 * @example
 *     {
 *         ttsText: "ttsText"
 *     }
 */
export interface GenerateTtsRequest {
    ttsText: string;
    /** From `GET /v1/resources/tts-voices`. Omitted or null uses server defaults. */
    voiceId?: string | null;
    previousTtsText?: string | null;
    nextTtsText?: string | null;
    /** Optional ISO-639-1 language hint for pronunciation (e.g. `en`, `es`, `zh`). The server validates the value at runtime against the supported set. */
    speechLanguageCode?: string | null;
    /** Defaults to false when omitted. */
    hideCaptions?: boolean;
    pronunciationReplacements?: VideogenApi.PronunciationReplacement[];
    /** Defaults to false when omitted. */
    autoExpandPronunciationReplacements?: boolean;
    /** Defaults to server voice default when omitted. */
    voiceSpeed?: number;
    /** How many file outputs to generate (1–100). */
    numCandidates?: number;
}
