// This file was auto-generated by Fern from our API Definition.

import type * as VideogenApi from "../../../../index.js";

/**
 * @example
 *     {
 *         presenterDescription: "presenterDescription"
 *     }
 */
export interface GenerateAvatarRequest {
    /** Natural-language description of the desired presenter. */
    presenterDescription: string;
    audio?: VideogenApi.AssetRef;
    /** Optional link to a prior TTS execution when chaining. */
    sourceTtsExecutionId?: string | null;
}
