// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         prompt: "prompt"
 *     }
 */
export interface GenerateSoundEffectRequest {
    prompt: string;
    durationSeconds?: number | null;
    promptInfluence?: number | null;
}
