// This file was auto-generated by Fern from our API Definition.

import type * as VideoGenApi from "../../../../index.js";

/**
 * @example
 *     {
 *         prompt: "A serene mountain landscape at sunrise with vibrant colors and mist",
 *         quality: "STANDARD"
 *     }
 *
 * @example
 *     {
 *         prompt: "Transform this photo into an oil painting style with warm autumn tones",
 *         quality: "STANDARD",
 *         imageFileIds: ["vg_file_obLD1OX2eJCrEs0071Z4kA"]
 *     }
 */
export interface GenerateImageRequest {
    /** Text prompt describing the image to generate. When reference images are provided, the prompt describes the desired transformation. */
    prompt: string;
    /** Optional file ids of reference images (e.g. `["vg_file_..."]`). Upload files first via `POST /v1/files/upload`, then pass the returned ids here. Maximum 4 images. When provided, the model uses these as guidance for generation. */
    imageFileIds?: string[];
    /** Aspect ratio for the generated image. Defaults to 16:9 when omitted. */
    aspectRatio?: VideoGenApi.AspectRatio;
    /** Image generation quality tier. LOW is fastest; HIGH is slowest and highest quality. */
    quality: GenerateImageRequest.Quality;
    watermarkMode?: VideoGenApi.WatermarkMode;
    /** Number of output results to generate. Defaults to 1. */
    numResults?: number;
    /** When true, generated files are temporary. Temporary files are guaranteed to be available for 24 hours, after which they may be archived at any time. Temporary files are not analyzed (no description, transcript, or embedding will be generated), so they will not appear in search results. Defaults to false. */
    isOutputTemporary?: boolean;
}

export namespace GenerateImageRequest {
    /** Image generation quality tier. LOW is fastest; HIGH is slowest and highest quality. */
    export const Quality = {
        Low: "LOW",
        Standard: "STANDARD",
        High: "HIGH",
    } as const;
    export type Quality = (typeof Quality)[keyof typeof Quality];
}
