// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         apiTaskExecutionId: "apiTaskExecutionId"
 *     }
 */
export interface GetExecutedToolRequest {
    apiTaskExecutionId: string;
}
