// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         imageStorageFileId: "imageStorageFileId"
 *     }
 */
export interface ImageToVideoClipRequest {
    /** File id of the source image (e.g. `vg_file_...`). Upload a file first via `POST /v1/files/upload`, then pass the returned id here. */
    imageStorageFileId: string;
    /** Optional text prompt to guide the animation. When omitted the model infers motion from the image. */
    prompt?: string;
    /** When true, the generated video is guaranteed to include audio. When false, audio may still be present. Defaults to false. */
    generateAudio?: boolean;
    /** Optional prompt used when the source image was generated. */
    sourcePromptToImagePrompt?: string | null;
    /** Number of output results to generate. Defaults to 1. */
    numResults?: number;
    /** When true, generated files are temporary. Temporary files are guaranteed to be available for 24 hours, after which they may be archived at any time. Temporary files are not analyzed (no description, transcript, or embedding will be generated), so they will not appear in search results. Defaults to false. */
    isOutputTemporary?: boolean;
}
