// This file was auto-generated by Fern from our API Definition.

import type * as VideogenApi from "../../../../index.js";

/**
 * @example
 *     {
 *         prompt: "prompt",
 *         generateAudio: true,
 *         image: {
 *             storageFileId: "storageFileId",
 *             type: "IMAGE"
 *         }
 *     }
 */
export interface ImageToVideoRequest {
    prompt: string;
    generateAudio: boolean;
    image: VideogenApi.StorageFileRef;
    /** Optional prompt used when the source image was generated. */
    sourcePromptToImagePrompt?: string | null;
    /** Number of output candidates to generate. Defaults to 1. */
    numCandidates?: number;
    /** When true, generated files are scoped as temporary. Defaults to false. */
    isOutputTemporary?: boolean;
}
