// This file was auto-generated by Fern from our API Definition.

import type * as VideogenApi from "../../../../index.js";

/**
 * @example
 *     {
 *         prompt: "prompt",
 *         image: {
 *             storageFileId: "storageFileId",
 *             type: "IMAGE"
 *         }
 *     }
 */
export interface ImageToImageRequest {
    /** Prompt describing how to transform the input image. */
    prompt: string;
    image: VideogenApi.StorageFileRef;
    /** Number of output candidates to generate. Defaults to 1. */
    numCandidates?: number;
    /** When true, generated files are scoped as temporary. Defaults to false. */
    isOutputTemporary?: boolean;
}
