// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         imageStorageFileId: "imageStorageFileId"
 *     }
 */
export interface ImageToVideoClipRequest {
    /** File id of the source image (e.g. `vg_file_...`). Upload a file first via `POST /v1/files/upload`, then pass the returned id here. */
    imageStorageFileId: string;
    /** Optional text prompt to guide the animation. When omitted the model infers motion from the image. */
    prompt?: string;
    /** Whether to generate audio alongside the video. Defaults to false. */
    generateAudio?: boolean;
    /** Optional prompt used when the source image was generated. */
    sourcePromptToImagePrompt?: string | null;
    /** Number of output candidates to generate. Defaults to 1. */
    numCandidates?: number;
    /** When true, generated files are temporary and automatically deleted after 24 hours. Defaults to false. */
    isOutputTemporary?: boolean;
}
