// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListToolExecutionsRequest {
    /** Maximum number of items to return in the page. Defaults to 50; capped at 200. See [Pagination](/pagination). */
    limit?: number;
    /** Opaque pagination cursor returned as `nextCursor` by the previous page. Omit on the first request. Cursors are tied to the endpoint that produced them and must be passed unmodified. See [Pagination](/pagination). */
    cursor?: string;
    /** When true, returns only items created by the API key's owner. When false (default), returns all items accessible to the team. */
    selfOnly?: boolean;
}
