// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         prompt: "prompt"
 *     }
 */
export interface PromptToSoundEffectRequest {
    prompt: string;
    durationSeconds?: number | null;
    promptInfluence?: number | null;
    /** Number of output candidates to generate. Defaults to 1. */
    numCandidates?: number;
    /** When true, generated files are scoped as temporary. Defaults to false. */
    isOutputTemporary?: boolean;
}
