// This file was auto-generated by Fern from our API Definition.

import type * as VideoGenApi from "../../../../index.js";

/**
 * @example
 *     {
 *         prompt: "A serene Japanese garden with cherry blossoms at golden hour"
 *     }
 */
export interface PromptToImageRequest {
    prompt: string;
    /** Aspect ratio for the generated image. Defaults to 16:9 when omitted. */
    aspectRatio?: VideoGenApi.AspectRatio;
    /** Number of output candidates to generate. Defaults to 1. */
    numCandidates?: number;
    /** When true, generated files are temporary. Temporary files are guaranteed to be available for 24 hours, after which they may be archived at any time. Defaults to false. */
    isOutputTemporary?: boolean;
}
