// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         prompt: "prompt"
 *     }
 */
export interface PromptToSoundEffectRequest {
    prompt: string;
    durationSeconds?: number | null;
    promptInfluence?: number | null;
    /** Number of output candidates to generate. Defaults to 1. */
    numCandidates?: number;
    /** When true, generated files are temporary. Temporary files are guaranteed to be available for 24 hours, after which they may be archived at any time. Temporary files are not analyzed (no description, transcript, or embedding will be generated), so they will not appear in search results. Defaults to false. */
    isOutputTemporary?: boolean;
}
