// This file was auto-generated by Fern from our API Definition.

import type * as VideoGenApi from "../../../../index.js";

/**
 * @example
 *     {
 *         ttsText: "ttsText"
 *     }
 */
export interface TextToSpeechRequest {
    ttsText: string;
    /** Voice id from `GET /v1/resources/tts-voices`. A default voice is used when null. Only voices with `supportsDirectToolExecution` set to true are accepted. */
    voiceId?: string | null;
    /** ISO-639-1 language hint for pronunciation (e.g. `en`, `es`, `zh`). */
    speechLanguageCode?: string | null;
    pronunciationReplacements?: VideoGenApi.PronunciationReplacement[];
    /** When true, automatically expands numbers, symbols, acronyms, and other non-word tokens into their spoken forms before synthesis so the voice pronounces them correctly (e.g. `$100` → `one hundred dollars`, `NASA` → `nasa`, `3rd` → `third`). Defaults to false when omitted. */
    autoExpandPronunciationReplacements?: boolean;
    /** Speech rate multiplier. Defaults to the voice's default speed. */
    voiceSpeed?: number;
    /** Number of output candidates to generate. Defaults to 1. */
    numCandidates?: number;
    /** When true, generated files are temporary. Temporary files are guaranteed to be available for 24 hours, after which they may be archived at any time. Temporary files are not analyzed (no description, transcript, or embedding will be generated), so they will not appear in search results. Defaults to false. */
    isOutputTemporary?: boolean;
}
