// This file was auto-generated by Fern from our API Definition.

import type * as VideogenApi from "../../../../index.js";

/**
 * @example
 *     {
 *         video: {
 *             storageFileId: "storageFileId",
 *             type: "IMAGE"
 *         }
 *     }
 */
export interface VideoAssetRequest {
    video: VideogenApi.StorageFile;
}
