// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         videoStorageFileId: "videoStorageFileId",
 *         prompt: "prompt"
 *     }
 */
export interface VideoToVideoClipRequest {
    /** File id of the source video (e.g. `vg_file_...`). Upload a file first via `POST /v1/files/upload`, then pass the returned id here. */
    videoStorageFileId: string;
    /** Prompt describing how to transform the input video. */
    prompt: string;
    /** Number of output candidates to generate. Defaults to 1. */
    numCandidates?: number;
    /** When true, generated files are temporary. Temporary files are guaranteed to be available for 24 hours, after which they may be archived at any time. Defaults to false. */
    isOutputTemporary?: boolean;
}
