// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListTtsVoicesRequest {
    /** When true, includes deprecated voices in the response. Defaults to false. */
    includeDeprecatedVoices?: boolean;
}
