// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         prompt: "Write a 30-second upbeat video script about why the sky is blue."
 *     }
 */
export interface GenerateTextRequest {
    /** The instruction or content to generate text from. */
    prompt: string;
    /** Optional system instructions that steer the model's role, tone, and constraints. */
    system?: string | null;
    /** Model quality tier. `LOW` is fastest and cheapest; `STANDARD` balances quality and cost; `HIGH` is highest quality. Defaults to `STANDARD`. */
    model?: GenerateTextRequest.Model;
    /** Sampling temperature. Higher values produce more varied output. Defaults to the model's default. */
    temperature?: number;
    /** Maximum number of tokens to generate. Defaults to 512. */
    maxOutputTokens?: number;
}

export namespace GenerateTextRequest {
    /** Model quality tier. `LOW` is fastest and cheapest; `STANDARD` balances quality and cost; `HIGH` is highest quality. Defaults to `STANDARD`. */
    export const Model = {
        Low: "LOW",
        Standard: "STANDARD",
        High: "HIGH",
    } as const;
    export type Model = (typeof Model)[keyof typeof Model];
}
