// This file was auto-generated by Fern from our API Definition.

import type * as VideoGenApi from "../../../../index.js";

/**
 * @example
 *     {
 *         fileId: "fileId",
 *         visualStyle: {
 *             type: "STOCK"
 *         }
 *     }
 */
export interface AddVisualsAndCaptionsToVoiceoverRequest {
    /** Opaque file id of an uploaded voiceover audio file (e.g. `vg_file_...`). Upload the file first via `POST /v1/files/upload`. */
    fileId: string;
    aspectRatio?: VideoGenApi.AspectRatio;
    visualStyle: VideoGenApi.WorkflowVisualStyle;
    visualPacing?: VideoGenApi.VisualPacing;
    /** Output language as a BCP-47 code (e.g. `en`, `es`, `fr`). Defaults to English. */
    language?: string;
    /** Caption styling. Omit to use the default style with captions shown. Pass an object to override individual style fields (any omitted field uses the default). Pass `null` to hide captions entirely. */
    captionStyle?: VideoGenApi.WorkflowCaptionStyle | null;
    /** Optional file id of an uploaded logo image to overlay on the video (e.g. `vg_file_...`). Upload the image first via `POST /v1/files/upload`. Only image files are accepted. */
    logoFileId?: string | null;
    /** Optional edits applied to the project after the video is built, in order. Each action runs asynchronously; the response returns one remix action id per action. Use this for background music, logo overlays, or caption changes beyond `captionStyle`. */
    remixActions?: VideoGenApi.RemixAction[];
}
