// This file was auto-generated by Fern from our API Definition.

import type * as VideoGenApi from "../../../../index.js";

/**
 * @example
 *     {
 *         script: "script"
 *     }
 */
export interface AddVisualsNarrationsAndCaptionsToScriptRequest {
    /** The narration script, used verbatim. This exact text is narrated and turned into a video — it is not rewritten or expanded. */
    script: string;
    aspectRatio?: VideoGenApi.AspectRatio;
}
