// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         workflowRunId: "workflowRunId"
 *     }
 */
export interface CancelWorkflowRunRequest {
    /** The workflow run id returned when the workflow was started. */
    workflowRunId: string;
}
