// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         workflowRunId: "vg_work_ccm3abc123defcm3xyz789ghi"
 *     }
 */
export interface GetWorkflowRunRequest {
    /** The workflow run id returned when the workflow was started. */
    workflowRunId: string;
}
