// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import type * as VideoGenApi from "../../../index.js";

export declare namespace ToolsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Generate images, videos, audio, and more. All tool endpoints are asynchronous.
 */
export class ToolsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ToolsClient.Options>;

    constructor(options: ToolsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Generate an image from a text prompt. Optionally specify an aspect ratio and number of candidates.
     *
     * @param {VideoGenApi.PromptToImageRequest} request
     * @param {ToolsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.tools.promptToImage({
     *         prompt: "prompt"
     *     })
     */
    public promptToImage(
        request: VideoGenApi.PromptToImageRequest,
        requestOptions?: ToolsClient.RequestOptions,
    ): core.HttpResponsePromise<VideoGenApi.StartToolExecutionResponse> {
        return core.HttpResponsePromise.fromPromise(this.__promptToImage(request, requestOptions));
    }

    private async __promptToImage(
        request: VideoGenApi.PromptToImageRequest,
        requestOptions?: ToolsClient.RequestOptions,
    ): Promise<core.WithRawResponse<VideoGenApi.StartToolExecutionResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.VideoGenEnvironment.Production,
                "v1/tools/prompt-to-image",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as VideoGenApi.StartToolExecutionResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.VideoGenError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/tools/prompt-to-image");
    }

    /**
     * Generate a video clip from a text prompt, with optional audio. Optionally specify an aspect ratio and number of candidates.
     *
     * @param {VideoGenApi.PromptToVideoClipRequest} request
     * @param {ToolsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.tools.promptToVideoClip({
     *         prompt: "prompt"
     *     })
     */
    public promptToVideoClip(
        request: VideoGenApi.PromptToVideoClipRequest,
        requestOptions?: ToolsClient.RequestOptions,
    ): core.HttpResponsePromise<VideoGenApi.StartToolExecutionResponse> {
        return core.HttpResponsePromise.fromPromise(this.__promptToVideoClip(request, requestOptions));
    }

    private async __promptToVideoClip(
        request: VideoGenApi.PromptToVideoClipRequest,
        requestOptions?: ToolsClient.RequestOptions,
    ): Promise<core.WithRawResponse<VideoGenApi.StartToolExecutionResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.VideoGenEnvironment.Production,
                "v1/tools/prompt-to-video-clip",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as VideoGenApi.StartToolExecutionResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.VideoGenError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/tools/prompt-to-video-clip",
        );
    }

    /**
     * Animate a still image into a video clip using a text prompt. Optionally generate audio alongside the video.
     *
     * @param {VideoGenApi.ImageToVideoClipRequest} request
     * @param {ToolsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.tools.imageToVideoClip({
     *         imageStorageFileId: "imageStorageFileId"
     *     })
     */
    public imageToVideoClip(
        request: VideoGenApi.ImageToVideoClipRequest,
        requestOptions?: ToolsClient.RequestOptions,
    ): core.HttpResponsePromise<VideoGenApi.StartToolExecutionResponse> {
        return core.HttpResponsePromise.fromPromise(this.__imageToVideoClip(request, requestOptions));
    }

    private async __imageToVideoClip(
        request: VideoGenApi.ImageToVideoClipRequest,
        requestOptions?: ToolsClient.RequestOptions,
    ): Promise<core.WithRawResponse<VideoGenApi.StartToolExecutionResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.VideoGenEnvironment.Production,
                "v1/tools/image-to-video-clip",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as VideoGenApi.StartToolExecutionResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.VideoGenError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/tools/image-to-video-clip",
        );
    }

    /**
     * Transform an existing image using a text prompt. The prompt describes the desired changes to apply.
     *
     * @param {VideoGenApi.ImageToImageRequest} request
     * @param {ToolsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.tools.imageToImage({
     *         imageStorageFileId: "imageStorageFileId",
     *         prompt: "prompt"
     *     })
     */
    public imageToImage(
        request: VideoGenApi.ImageToImageRequest,
        requestOptions?: ToolsClient.RequestOptions,
    ): core.HttpResponsePromise<VideoGenApi.StartToolExecutionResponse> {
        return core.HttpResponsePromise.fromPromise(this.__imageToImage(request, requestOptions));
    }

    private async __imageToImage(
        request: VideoGenApi.ImageToImageRequest,
        requestOptions?: ToolsClient.RequestOptions,
    ): Promise<core.WithRawResponse<VideoGenApi.StartToolExecutionResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.VideoGenEnvironment.Production,
                "v1/tools/image-to-image",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as VideoGenApi.StartToolExecutionResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.VideoGenError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/tools/image-to-image");
    }

    /**
     * Restyle an existing video using a text prompt. The prompt describes the visual transformation to apply.
     *
     * @param {VideoGenApi.VideoToVideoClipRequest} request
     * @param {ToolsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.tools.videoToVideoClip({
     *         videoStorageFileId: "videoStorageFileId",
     *         prompt: "prompt"
     *     })
     */
    public videoToVideoClip(
        request: VideoGenApi.VideoToVideoClipRequest,
        requestOptions?: ToolsClient.RequestOptions,
    ): core.HttpResponsePromise<VideoGenApi.StartToolExecutionResponse> {
        return core.HttpResponsePromise.fromPromise(this.__videoToVideoClip(request, requestOptions));
    }

    private async __videoToVideoClip(
        request: VideoGenApi.VideoToVideoClipRequest,
        requestOptions?: ToolsClient.RequestOptions,
    ): Promise<core.WithRawResponse<VideoGenApi.StartToolExecutionResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.VideoGenEnvironment.Production,
                "v1/tools/video-to-video-clip",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as VideoGenApi.StartToolExecutionResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.VideoGenError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/tools/video-to-video-clip",
        );
    }

    /**
     * Convert text into a spoken audio file. Only voices with `supportsDirectToolExecution` set to true can be used. Optionally choose a voice, language, speed, and pronunciation overrides.
     *
     * @param {VideoGenApi.TextToSpeechRequest} request
     * @param {ToolsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.tools.textToSpeech({
     *         ttsText: "ttsText"
     *     })
     */
    public textToSpeech(
        request: VideoGenApi.TextToSpeechRequest,
        requestOptions?: ToolsClient.RequestOptions,
    ): core.HttpResponsePromise<VideoGenApi.StartToolExecutionResponse> {
        return core.HttpResponsePromise.fromPromise(this.__textToSpeech(request, requestOptions));
    }

    private async __textToSpeech(
        request: VideoGenApi.TextToSpeechRequest,
        requestOptions?: ToolsClient.RequestOptions,
    ): Promise<core.WithRawResponse<VideoGenApi.StartToolExecutionResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.VideoGenEnvironment.Production,
                "v1/tools/text-to-speech",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as VideoGenApi.StartToolExecutionResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.VideoGenError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/tools/text-to-speech");
    }

    /**
     * Generate a sound effect from a text description. Optionally control the duration and prompt influence.
     *
     * @param {VideoGenApi.PromptToSoundEffectRequest} request
     * @param {ToolsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.tools.promptToSoundEffect({
     *         prompt: "prompt"
     *     })
     */
    public promptToSoundEffect(
        request: VideoGenApi.PromptToSoundEffectRequest,
        requestOptions?: ToolsClient.RequestOptions,
    ): core.HttpResponsePromise<VideoGenApi.StartToolExecutionResponse> {
        return core.HttpResponsePromise.fromPromise(this.__promptToSoundEffect(request, requestOptions));
    }

    private async __promptToSoundEffect(
        request: VideoGenApi.PromptToSoundEffectRequest,
        requestOptions?: ToolsClient.RequestOptions,
    ): Promise<core.WithRawResponse<VideoGenApi.StartToolExecutionResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.VideoGenEnvironment.Production,
                "v1/tools/prompt-to-sound-effect",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as VideoGenApi.StartToolExecutionResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.VideoGenError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/tools/prompt-to-sound-effect",
        );
    }

    /**
     * Generate a talking-head avatar video by pairing a presenter with an audio file, typically from a prior text-to-speech result.
     *
     * @param {VideoGenApi.AudioToAvatarClipRequest} request
     * @param {ToolsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.tools.audioToAvatarClip({
     *         avatarPresenterId: "avatarPresenterId",
     *         audioStorageFileId: "audioStorageFileId"
     *     })
     */
    public audioToAvatarClip(
        request: VideoGenApi.AudioToAvatarClipRequest,
        requestOptions?: ToolsClient.RequestOptions,
    ): core.HttpResponsePromise<VideoGenApi.StartToolExecutionResponse> {
        return core.HttpResponsePromise.fromPromise(this.__audioToAvatarClip(request, requestOptions));
    }

    private async __audioToAvatarClip(
        request: VideoGenApi.AudioToAvatarClipRequest,
        requestOptions?: ToolsClient.RequestOptions,
    ): Promise<core.WithRawResponse<VideoGenApi.StartToolExecutionResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.VideoGenEnvironment.Production,
                "v1/tools/audio-to-avatar-clip",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as VideoGenApi.StartToolExecutionResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.VideoGenError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/tools/audio-to-avatar-clip",
        );
    }

    /**
     * Convert any raster image into a scalable vector graphic (SVG). The output traces the shapes and colors of the input image.
     *
     * @param {VideoGenApi.ImageAssetRequest} request
     * @param {ToolsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.tools.vectorizeImage({
     *         imageStorageFileId: "imageStorageFileId"
     *     })
     */
    public vectorizeImage(
        request: VideoGenApi.ImageAssetRequest,
        requestOptions?: ToolsClient.RequestOptions,
    ): core.HttpResponsePromise<VideoGenApi.StartToolExecutionResponse> {
        return core.HttpResponsePromise.fromPromise(this.__vectorizeImage(request, requestOptions));
    }

    private async __vectorizeImage(
        request: VideoGenApi.ImageAssetRequest,
        requestOptions?: ToolsClient.RequestOptions,
    ): Promise<core.WithRawResponse<VideoGenApi.StartToolExecutionResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.VideoGenEnvironment.Production,
                "v1/tools/vectorize-image",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as VideoGenApi.StartToolExecutionResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.VideoGenError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/tools/vectorize-image");
    }

    /**
     * Remove the background from an image, returning a transparent-background PNG of the foreground subject.
     *
     * @param {VideoGenApi.ImageAssetRequest} request
     * @param {ToolsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.tools.removeImageBackground({
     *         imageStorageFileId: "imageStorageFileId"
     *     })
     */
    public removeImageBackground(
        request: VideoGenApi.ImageAssetRequest,
        requestOptions?: ToolsClient.RequestOptions,
    ): core.HttpResponsePromise<VideoGenApi.StartToolExecutionResponse> {
        return core.HttpResponsePromise.fromPromise(this.__removeImageBackground(request, requestOptions));
    }

    private async __removeImageBackground(
        request: VideoGenApi.ImageAssetRequest,
        requestOptions?: ToolsClient.RequestOptions,
    ): Promise<core.WithRawResponse<VideoGenApi.StartToolExecutionResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.VideoGenEnvironment.Production,
                "v1/tools/remove-image-background",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as VideoGenApi.StartToolExecutionResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.VideoGenError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/tools/remove-image-background",
        );
    }

    /**
     * Remove the background from a video, producing a transparent-background video of the foreground subject.
     *
     * @param {VideoGenApi.VideoAssetRequest} request
     * @param {ToolsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.tools.removeVideoBackground({
     *         videoStorageFileId: "videoStorageFileId"
     *     })
     */
    public removeVideoBackground(
        request: VideoGenApi.VideoAssetRequest,
        requestOptions?: ToolsClient.RequestOptions,
    ): core.HttpResponsePromise<VideoGenApi.StartToolExecutionResponse> {
        return core.HttpResponsePromise.fromPromise(this.__removeVideoBackground(request, requestOptions));
    }

    private async __removeVideoBackground(
        request: VideoGenApi.VideoAssetRequest,
        requestOptions?: ToolsClient.RequestOptions,
    ): Promise<core.WithRawResponse<VideoGenApi.StartToolExecutionResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.VideoGenEnvironment.Production,
                "v1/tools/remove-video-background",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as VideoGenApi.StartToolExecutionResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.VideoGenError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/tools/remove-video-background",
        );
    }

    /**
     * Increase the resolution of an image while preserving detail and sharpness.
     *
     * @param {VideoGenApi.ImageAssetRequest} request
     * @param {ToolsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.tools.upscaleImage({
     *         imageStorageFileId: "imageStorageFileId"
     *     })
     */
    public upscaleImage(
        request: VideoGenApi.ImageAssetRequest,
        requestOptions?: ToolsClient.RequestOptions,
    ): core.HttpResponsePromise<VideoGenApi.StartToolExecutionResponse> {
        return core.HttpResponsePromise.fromPromise(this.__upscaleImage(request, requestOptions));
    }

    private async __upscaleImage(
        request: VideoGenApi.ImageAssetRequest,
        requestOptions?: ToolsClient.RequestOptions,
    ): Promise<core.WithRawResponse<VideoGenApi.StartToolExecutionResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.VideoGenEnvironment.Production,
                "v1/tools/upscale-image",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as VideoGenApi.StartToolExecutionResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.VideoGenError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/tools/upscale-image");
    }

    /**
     * Increase the resolution of a video while preserving detail and sharpness.
     *
     * @param {VideoGenApi.VideoAssetRequest} request
     * @param {ToolsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.tools.upscaleVideo({
     *         videoStorageFileId: "videoStorageFileId"
     *     })
     */
    public upscaleVideo(
        request: VideoGenApi.VideoAssetRequest,
        requestOptions?: ToolsClient.RequestOptions,
    ): core.HttpResponsePromise<VideoGenApi.StartToolExecutionResponse> {
        return core.HttpResponsePromise.fromPromise(this.__upscaleVideo(request, requestOptions));
    }

    private async __upscaleVideo(
        request: VideoGenApi.VideoAssetRequest,
        requestOptions?: ToolsClient.RequestOptions,
    ): Promise<core.WithRawResponse<VideoGenApi.StartToolExecutionResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.VideoGenEnvironment.Production,
                "v1/tools/upscale-video",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as VideoGenApi.StartToolExecutionResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.VideoGenError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/tools/upscale-video");
    }

    /**
     * Request cancellation of a running tool execution. The execution transitions to `cancelled` if it has not already completed.
     *
     * @param {VideoGenApi.CancelToolExecutionRequest} request
     * @param {ToolsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.tools.cancelToolExecution({
     *         toolExecutionId: "toolExecutionId"
     *     })
     */
    public cancelToolExecution(
        request: VideoGenApi.CancelToolExecutionRequest,
        requestOptions?: ToolsClient.RequestOptions,
    ): core.HttpResponsePromise<VideoGenApi.StartToolExecutionResponse> {
        return core.HttpResponsePromise.fromPromise(this.__cancelToolExecution(request, requestOptions));
    }

    private async __cancelToolExecution(
        request: VideoGenApi.CancelToolExecutionRequest,
        requestOptions?: ToolsClient.RequestOptions,
    ): Promise<core.WithRawResponse<VideoGenApi.StartToolExecutionResponse>> {
        const { toolExecutionId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.VideoGenEnvironment.Production,
                `v1/tools/executions/${core.url.encodePathParam(toolExecutionId)}/cancel`,
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as VideoGenApi.StartToolExecutionResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.VideoGenError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/tools/executions/{toolExecutionId}/cancel",
        );
    }

    /**
     * Retrieve the current status and result of a tool execution. Poll this endpoint until `status` is `succeeded`, `failed`, or `cancelled`.
     *
     * @param {VideoGenApi.GetToolExecutionInfoRequest} request
     * @param {ToolsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.tools.getToolExecutionInfo({
     *         toolExecutionId: "toolExecutionId"
     *     })
     */
    public getToolExecutionInfo(
        request: VideoGenApi.GetToolExecutionInfoRequest,
        requestOptions?: ToolsClient.RequestOptions,
    ): core.HttpResponsePromise<VideoGenApi.ExecutedTool> {
        return core.HttpResponsePromise.fromPromise(this.__getToolExecutionInfo(request, requestOptions));
    }

    private async __getToolExecutionInfo(
        request: VideoGenApi.GetToolExecutionInfoRequest,
        requestOptions?: ToolsClient.RequestOptions,
    ): Promise<core.WithRawResponse<VideoGenApi.ExecutedTool>> {
        const { toolExecutionId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.VideoGenEnvironment.Production,
                `v1/tools/executions/${core.url.encodePathParam(toolExecutionId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as VideoGenApi.ExecutedTool, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.VideoGenError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v1/tools/executions/{toolExecutionId}",
        );
    }
}
