// This file was auto-generated by Fern from our API Definition.

import type * as VideoGenApi from "../../../../index.js";

/**
 * @example
 *     {
 *         projectId: "1f0a2b3c-4d5e-6789-ab12-cdef34567890",
 *         quality: "FULL_HIGH"
 *     }
 */
export interface ExportProjectRequest {
    /** The project id (e.g. `vg_proj_...`). */
    projectId: string;
    quality?: VideoGenApi.ExportProjectQuality;
}
