// This file was auto-generated by Fern from our API Definition.

import type * as VideoGenApi from "../../../../index.js";

/**
 * @example
 *     {
 *         projectId: "vg_proj_9dTk3mQ1rZ7xP4vN2sB6wc",
 *         quality: "FULL_HIGH"
 *     }
 */
export interface ExportProjectRequest {
    /** The project id (e.g. `vg_proj_...`). */
    projectId: string;
    quality?: VideoGenApi.ExportProjectQuality;
    /** Destinations to deliver the finished export to when it completes, in addition to any delivery destinations already saved for the team. Each destination references a connected integration. */
    deliveryDestinations?: VideoGenApi.ExportDeliveryDestination[];
}
