// This file was auto-generated by Fern from our API Definition.

import type * as VideoGenApi from "../../../../index.js";

/**
 * @example
 *     {
 *         projectId: "projectId"
 *     }
 */
export interface ExportProjectRequest {
    /** The project id (e.g. `vg_proj_...`). */
    projectId: string;
    quality?: VideoGenApi.ExportProjectQuality;
}
