// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         projectId: "1f0a2b3c-4d5e-6789-ab12-cdef34567890"
 *     }
 */
export interface GetProjectRequest {
    /** The project id (e.g. `vg_proj_...`). */
    projectId: string;
}
