// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         projectId: "vg_proj_9dTk3mQ1rZ7xP4vN2sB6wc",
 *         exportId: "vg_expo_4bHn8pR2sY5xM1vL3tC7wd"
 *     }
 */
export interface GetProjectExportRequest {
    /** The project id (e.g. `vg_proj_...`). */
    projectId: string;
    /** The export id (e.g. `vg_expo_...`) returned by `POST /v1/projects/{projectId}/export`. */
    exportId: string;
}
