// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         projectId: "projectId"
 *     }
 */
export interface ListProjectRemixActionsRequest {
    /** The project id (e.g. `vg_proj_...`). */
    projectId: string;
}
