// This file was auto-generated by Fern from our API Definition.

import type * as VideoGenApi from "../../../../index.js";

/**
 * @example
 *     {
 *         projectId: "projectId",
 *         remixActions: [{
 *                 type: "SET_BACKGROUND_MUSIC"
 *             }]
 *     }
 */
export interface RemixProjectRequest {
    /** The project id (e.g. `vg_proj_...`). */
    projectId: string;
    /** Ordered list of edits to apply. Each runs asynchronously as its own remix action. */
    remixActions: VideoGenApi.RemixAction[];
    /** When true, the project is duplicated first and the edits are applied to the copy, leaving the original untouched. The response's `projectId` is the copy. Defaults to false (edits the project in place). */
    saveAsNewProject?: boolean;
}
