// This file was auto-generated by Fern from our API Definition.

export interface ApiError {
    /** Human-readable error description. */
    message: string;
    /** Machine-readable error code in snake_case (e.g. `invalid_api_key`, `insufficient_credits`). Not always present. */
    code?: string | undefined;
    /** Opaque internal error code for debugging. Include this when contacting support. */
    internalErrorCode?: string | undefined;
}
