// This file was auto-generated by Fern from our API Definition.

/**
 * Aspect ratio as a width:height pair (e.g. 16 and 9 for 16:9). Not pixel dimensions.
 */
export interface AspectRatio {
    width: number;
    height: number;
}
