// This file was auto-generated by Fern from our API Definition.

/**
 * Reference to an uploaded file or a public URL.
 */
export type AssetRef =
    | {
          fileId: string;
      }
    | {
          url: string;
      };
