// This file was auto-generated by Fern from our API Definition.

import type * as VideoGenApi from "../index.js";

/**
 * An actionable widget the assistant offered on this turn. Act on it with `POST /v1/assistant/chats/{projectId}/actions/{actionId}` unless `requiresApp` is true.
 */
export interface AssistantAction {
    /** Opaque id to pass to the act-on-action endpoint. */
    actionId: string;
    kind: VideoGenApi.AssistantActionKind;
    /** Human-readable label describing what acting on this will do. */
    label: string;
    /** When true, this action can only be completed in the web app; open `projectUrl` instead of calling the API. */
    requiresApp: boolean;
}
