// This file was auto-generated by Fern from our API Definition.

/** Normalized category of an actionable widget the assistant offered. `APPROVE_PLAN` accepts a proposed generation plan; `APPLY_EDIT` applies a proposed edit (e.g. a rewritten script); `RUN_TOOL` runs an inline tool; `GENERATE` starts building the video; `OPEN_IN_APP` requires the full web app — open `projectUrl` instead of acting via the API. */
export const AssistantActionKind = {
    ApprovePlan: "APPROVE_PLAN",
    ApplyEdit: "APPLY_EDIT",
    RunTool: "RUN_TOOL",
    Generate: "GENERATE",
    OpenInApp: "OPEN_IN_APP",
} as const;
export type AssistantActionKind = (typeof AssistantActionKind)[keyof typeof AssistantActionKind];
