// This file was auto-generated by Fern from our API Definition.

/** Whether a video generation is now in progress as a result of this turn. */
export const AssistantTurnStatus = {
    Idle: "idle",
    Generating: "generating",
} as const;
export type AssistantTurnStatus = (typeof AssistantTurnStatus)[keyof typeof AssistantTurnStatus];
