// This file was auto-generated by Fern from our API Definition.

import type * as VideoGenApi from "../index.js";

/**
 * The assistant's reply for a turn, including any suggestions and actions it offered.
 */
export interface AssistantTurnResponse {
    /** Opaque project id for this chat (e.g. `vg_proj_...`). Pass it back to continue the conversation. */
    projectId: string;
    /** Deep link to open this project's chat in the VideoGen web app, where any action can be completed. Visible only to members of your team and project collaborators. */
    projectUrl: string;
    /** The assistant's text reply for this turn. May be empty when the assistant only offered widgets. */
    reply: string;
    /** Workflow starting points the assistant suggested. Empty when none were offered. */
    workflowSuggestions: VideoGenApi.AssistantWorkflowSuggestion[];
    /** Actionable widgets the assistant offered (plans, edits, tools, generate). Empty when none were offered. */
    actions: VideoGenApi.AssistantAction[];
    status: VideoGenApi.AssistantTurnStatus;
    /** Present when `status` is `generating`: the workflow run to poll via `GET /v1/workflows/runs/{workflowRunId}`. */
    generation?: (VideoGenApi.StartWorkflowRunResponse | null) | undefined;
}
