// This file was auto-generated by Fern from our API Definition.

import type * as VideogenApi from "../index.js";

export interface AvatarPresenterListResponse {
    avatarPresenters: VideogenApi.AvatarPresenter[];
}
