// This file was auto-generated by Fern from our API Definition.

/**
 * An avatar presenter available for video generation.
 */
export interface AvatarPresenter {
    /** Presenter id (e.g. `vg_pres_...`). Pass as `avatarPresenterId` to `POST /v1/tools/generate-avatar`. */
    avatarPresenterId: string;
    /** Presenter gender. */
    displayableGender: AvatarPresenter.DisplayableGender;
    /** Still image of the presenter. */
    imageUrl: string;
    /** Thumbnail image of the presenter. */
    thumbnailUrl: string;
    /** Short preview clip of the presenter speaking. */
    previewVideoUrl: string;
}

export namespace AvatarPresenter {
    /** Presenter gender. */
    export const DisplayableGender = {
        Male: "MALE",
        Female: "FEMALE",
        Neutral: "NEUTRAL",
    } as const;
    export type DisplayableGender = (typeof DisplayableGender)[keyof typeof DisplayableGender];
}
