// This file was auto-generated by Fern from our API Definition.

/**
 * A presenter you can use with `POST /v1/tools/generate-avatar` via `avatarPresenterId`.
 */
export interface AvatarPresenter {
    /** Pass as `avatarPresenterId` in `POST /v1/tools/generate-avatar`. */
    avatarPresenterId: string;
    /** Visual gender presentation of the presenter. */
    displayableGender: AvatarPresenter.DisplayableGender;
    /** Still image of the presenter. */
    imageUrl: string;
    /** Smaller image of the presenter, suitable for thumbnails or list rows. */
    thumbnailUrl: string;
    /** Short preview clip of the presenter speaking. */
    previewVideoUrl: string;
}

export namespace AvatarPresenter {
    /** Visual gender presentation of the presenter. */
    export const DisplayableGender = {
        Male: "MALE",
        Female: "FEMALE",
        Neutral: "NEUTRAL",
    } as const;
    export type DisplayableGender = (typeof DisplayableGender)[keyof typeof DisplayableGender];
}
