// This file was auto-generated by Fern from our API Definition.

export interface EntityArchiveResponse {
    /** The id of the archived entity. */
    entityId: string;
    /** Always true on success. */
    archived: boolean;
}
