// This file was auto-generated by Fern from our API Definition.

/**
 * Read-only voice and presenter summary for an ACTOR entity. Always null for VISUAL_STYLE entities.
 */
export interface EntityActorConfig {
    /** Display name of the actor's voice when one is configured. Null otherwise. */
    voiceDisplayName?: (string | null) | undefined;
    /** True when the actor has a configured voice. */
    hasVoice: boolean;
    /** True when the actor has a configured avatar presenter. */
    hasAvatarPresenter: boolean;
}
