// This file was auto-generated by Fern from our API Definition.

/**
 * A file attached to an entity as a reference image.
 */
export interface EntityReference {
    /** The reference image file id (e.g. `vg_file_...`). Hydrate it via `GET /v1/files/{fileId}` to fetch a viewable URL. */
    fileId: string;
    /** Optional description of the reference. Empty string when not set. */
    description: string;
    /** When true, this is the entity's primary reference (used for its thumbnail). */
    isDefault: boolean;
}
