// This file was auto-generated by Fern from our API Definition.

import type * as VideoGenApi from "../index.js";

/**
 * A reusable actor or visual style. Attach its reference images to workflows for consistent characters and looks.
 */
export interface Entity {
    /** The entity id (e.g. `vg_enti_...`). */
    entityId: string;
    /** ACTOR features a consistent character; VISUAL_STYLE guides the look of generated images. */
    entityType: Entity.EntityType;
    /** Display name. */
    name: string;
    /** Optional description. Empty string when not set. */
    description: string;
    /** Voice and presenter summary for ACTOR entities. Null for VISUAL_STYLE entities. */
    actorConfig?: (VideoGenApi.EntityActorConfig | null) | undefined;
    /** Reference images attached to the entity. */
    references: VideoGenApi.EntityReference[];
    /** When the entity was created (ISO 8601). */
    createdAt: string;
    /** When the entity was last updated (ISO 8601). */
    updatedAt: string;
}

export namespace Entity {
    /** ACTOR features a consistent character; VISUAL_STYLE guides the look of generated images. */
    export const EntityType = {
        Actor: "ACTOR",
        VisualStyle: "VISUAL_STYLE",
    } as const;
    export type EntityType = (typeof EntityType)[keyof typeof EntityType];
}
