// This file was auto-generated by Fern from our API Definition.

import type * as VideogenApi from "../index.js";

export interface ExecutedTool {
    /** Same opaque execution id returned from `POST /v1/tools/...`. */
    apiTaskExecutionId: string;
    status: VideogenApi.ExecutedToolStatus;
    /** Logical tool name (e.g. PROMPT_TO_IMAGE, PROMPT_TO_VIDEO_CLIP). */
    toolType: string;
    result?: VideogenApi.ToolSuccessResult | undefined;
    error?: VideogenApi.ApiError | undefined;
}
