// This file was auto-generated by Fern from our API Definition.

import type * as VideoGenApi from "../index.js";

export interface ExecutedTool {
    /** Execution id matching the original request. */
    toolExecutionId: string;
    status: VideoGenApi.ExecutedToolStatus;
    /** Tool name (e.g. `GENERATE_IMAGE`, `TEXT_TO_SPEECH`). */
    toolType: string;
    /** One entry per generated result. Present when `status` is `succeeded`. */
    results?: VideoGenApi.ToolSuccessResult[] | undefined;
    error?: VideoGenApi.ApiError | undefined;
}
