// This file was auto-generated by Fern from our API Definition.

/** `pending` and `running` are in-progress; `succeeded`, `failed`, and `cancelled` are terminal. */
export const ExecutedToolStatus = {
    Pending: "pending",
    Running: "running",
    Succeeded: "succeeded",
    Failed: "failed",
    Cancelled: "cancelled",
} as const;
export type ExecutedToolStatus = (typeof ExecutedToolStatus)[keyof typeof ExecutedToolStatus];
