// This file was auto-generated by Fern from our API Definition.

/** Non-terminal states may transition; terminal states end polling. */
export const ExecutedToolStatus = {
    Pending: "pending",
    Running: "running",
    Succeeded: "succeeded",
    Failed: "failed",
    Cancelled: "cancelled",
} as const;
export type ExecutedToolStatus = (typeof ExecutedToolStatus)[keyof typeof ExecutedToolStatus];
