// This file was auto-generated by Fern from our API Definition.

export interface ExportProjectResponse {
    /** Opaque export id. Poll `GET /v1/projects/{projectId}/exports/{exportId}` or subscribe to webhooks for completion. */
    exportId: string;
}
