// This file was auto-generated by Fern from our API Definition.

export interface ExportDeliveryDestination {
    /** Id of the connected integration that will receive this export. */
    integrationConnectionId: string;
    /** Where to deliver the export within the connected integration. */
    type: ExportDeliveryDestination.Type;
    /** Target channel id. Required when `type` is `slack_channel`. */
    slackChannelId?: (string | null) | undefined;
    /** Target folder id. Required when `type` is `google_drive_folder`. */
    googleDriveFolderId?: (string | null) | undefined;
}

export namespace ExportDeliveryDestination {
    /** Where to deliver the export within the connected integration. */
    export const Type = {
        SlackChannel: "slack_channel",
        GoogleDriveFolder: "google_drive_folder",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
