// This file was auto-generated by Fern from our API Definition.

/** Vertical resolution tier for the rendered MP4. */
export const ExportProjectQuality = {
    Standard: "STANDARD",
    High: "HIGH",
    FullHigh: "FULL_HIGH",
    UltraHigh: "ULTRA_HIGH",
} as const;
export type ExportProjectQuality = (typeof ExportProjectQuality)[keyof typeof ExportProjectQuality];
