// This file was auto-generated by Fern from our API Definition.

import type * as VideoGenApi from "../index.js";

/**
 * Delivered to your webhook endpoint during the file upload lifecycle. Only sent for files uploaded via the API. The payload always includes a hydrated `file` object with the latest state.
 */
export interface FileUploadWebhookPayload {
    event: VideoGenApi.FileUploadWebhookEventName;
    /** File id (e.g. `vg_file_...`). */
    fileId: string;
    /** Seconds since epoch (Unix timestamp) when the event occurred. */
    occurredAt: number;
    /** Hydrated file object with the latest state at the time of the event. */
    file: VideoGenApi.StorageFile;
    /** Error details. Present only on `file.upload.failed` and `file.analysis_failed`. */
    error?: VideoGenApi.ApiError | undefined;
}
