// This file was auto-generated by Fern from our API Definition.

export interface FileUploadResponse {
    /** The file id to use in subsequent API calls (e.g. `vg_file_...`). */
    fileId: string;
    /** Pre-signed URL. PUT the raw file bytes to this URL to complete the upload. */
    uploadUrl: string;
}
