// This file was auto-generated by Fern from our API Definition.

/** Webhook event types for file upload lifecycle. Only fired for files uploaded via the API (not the VideoGen UI). */
export const FileUploadWebhookEventName = {
    FileUploadCompleted: "file.upload.completed",
    FileUploadFailed: "file.upload.failed",
    FilePlaybackReady: "file.playback_ready",
    FileDownloadReady: "file.download_ready",
    FileAnalysisCompleted: "file.analysis_completed",
    FileAnalysisFailed: "file.analysis_failed",
} as const;
export type FileUploadWebhookEventName = (typeof FileUploadWebhookEventName)[keyof typeof FileUploadWebhookEventName];
