// This file was auto-generated by Fern from our API Definition.

/**
 * Background analysis state for a file. Background analysis populates `description`, `transcript`, `durationSeconds`, and the search embedding after a file is uploaded or generated; this object lets you render a progress indicator while it runs (and skip rendering once it's done).
 */
export interface FileAnalysisMetadata {
    /**
     * Coarse-grained analysis state.
     *
     * - `UNATTEMPTED`: analysis has not started yet.
     * - `LOADING`: analysis is in progress.
     * - `FULFILLED`: analysis completed successfully. `description`, `transcript`, and `durationSeconds` are now populated where applicable for the file's type.
     * - `REJECTED`: analysis failed permanently and will not be retried.
     */
    analysisLoadingState: FileAnalysisMetadata.AnalysisLoadingState;
    /** Progress in `[0, 100]`. Always `100` when `analysisLoadingState` is `FULFILLED`. Otherwise the most recent in-flight progress reported by the analysis task (or `0` if no progress has been reported yet). */
    analysisProgressPercentage: number;
    /** Zero-based index of the current analysis task attempt. Only present while analysis is still loading (`UNATTEMPTED` or `LOADING`); omitted once analysis reaches a terminal state. */
    analysisAttemptIndex?: number | undefined;
}

export namespace FileAnalysisMetadata {
    /**
     * Coarse-grained analysis state.
     *
     * - `UNATTEMPTED`: analysis has not started yet.
     * - `LOADING`: analysis is in progress.
     * - `FULFILLED`: analysis completed successfully. `description`, `transcript`, and `durationSeconds` are now populated where applicable for the file's type.
     * - `REJECTED`: analysis failed permanently and will not be retried.
     */
    export const AnalysisLoadingState = {
        Unattempted: "UNATTEMPTED",
        Loading: "LOADING",
        Fulfilled: "FULFILLED",
        Rejected: "REJECTED",
    } as const;
    export type AnalysisLoadingState = (typeof AnalysisLoadingState)[keyof typeof AnalysisLoadingState];
}
