// This file was auto-generated by Fern from our API Definition.

import type * as VideoGenApi from "../index.js";

/**
 * A single scene in the storyboard. Becomes one section in the final video.
 */
export interface GenerateStoryboardScene {
    /** What to generate for this scene. */
    prompt: string;
    /** Optional section name for this scene. Defaults to a numbered name. */
    title?: string | undefined;
    /** Optional per-scene generation override. Falls back to the request-level `defaultGeneration` when omitted. */
    generation?: (VideoGenApi.SceneGeneration | null) | undefined;
    /** Optional per-scene duration in seconds. Falls back to `defaultDurationSeconds` when omitted. For AI_VIDEO scenes this must be a whole number between 1 and 15. */
    durationSeconds?: (number | null) | undefined;
    /** Optional id of an ACTOR entity (e.g. `vg_enti_...`) to feature in this scene. The entity's reference images are added so the same character appears in the generated image or video. */
    actorEntityId?: (string | null) | undefined;
    /** Optional id of a VISUAL_STYLE entity (e.g. `vg_enti_...`) whose reference images guide the look of this scene. */
    visualStyleEntityId?: (string | null) | undefined;
    /** Optional voiceover script for this scene. When provided, text-to-speech audio is generated from this text, then combined with the actor entity's reference image to produce a talking-head avatar video. The TTS voice is sourced from the actor entity's voice configuration. */
    voiceoverScript?: (string | null) | undefined;
}
