// This file was auto-generated by Fern from our API Definition.

export interface ImageAssetRequest {
    /** File id of the source image (e.g. `vg_file_...`). Upload a file first via `POST /v1/files/upload`, then pass the returned id here. */
    imageStorageFileId: string;
    /** Number of output candidates to generate. Defaults to 1. */
    numCandidates?: number | undefined;
    /** When true, generated files are temporary and automatically deleted after 24 hours. Defaults to false. */
    isOutputTemporary?: boolean | undefined;
}
