// This file was auto-generated by Fern from our API Definition.

import type * as VideogenApi from "../index.js";

export interface ImageAssetRequest {
    image: VideogenApi.StorageFileRef;
    /** Number of output candidates to generate. Defaults to 1. */
    numCandidates?: number | undefined;
    /** When true, generated files are scoped as temporary. Defaults to false. */
    isOutputTemporary?: boolean | undefined;
}
