// This file was auto-generated by Fern from our API Definition.

/**
 * A language a project can be translated into.
 */
export interface Language {
    /** The language code to pass to a `TRANSLATE_PROJECT` remix action (e.g. `es`, `fr`, `ja`). */
    languageCode: string;
    /** Human-readable English name of the language (e.g. `Spanish`). */
    name: string;
}
