// This file was auto-generated by Fern from our API Definition.

import type * as VideoGenApi from "../index.js";

/**
 * Paginated list of API-created projects, most recently updated first.
 */
export interface ListProjectsResponse {
    projects: VideoGenApi.ProjectResponse[];
    /** When true, there are more projects available. Pass `nextCursor` as the `cursor` query param to fetch the next page. */
    hasMore: boolean;
    /** Opaque cursor to fetch the next page. `null` when `hasMore` is false. */
    nextCursor: string | null;
}
