// This file was auto-generated by Fern from our API Definition.

import type * as VideoGenApi from "../index.js";

/**
 * Paginated list of projects, most recently updated first. By default only API-created projects are included; pass `includeUiProjects=true` on the request to also include dashboard-created projects.
 */
export interface ListProjectsResponse {
    projects: VideoGenApi.ProjectResponse[];
    /** When true, there are more projects available. Pass `nextCursor` as the `cursor` query param to fetch the next page. */
    hasMore: boolean;
    /** Opaque cursor to fetch the next page. `null` when `hasMore` is false. */
    nextCursor: string | null;
}
