// This file was auto-generated by Fern from our API Definition.

import type * as VideoGenApi from "../index.js";

export interface ListRemixActionsResponse {
    /** Remix actions for the project, most recent first. */
    remixActions: VideoGenApi.RemixActionRun[];
}
