// This file was auto-generated by Fern from our API Definition.

export interface Pet {
    /** Unique identifier for the pet. */
    id: string;
    /** Name of the pet. */
    name: string;
    /** Optional tag for the pet. */
    tag?: string | undefined;
}
