// This file was auto-generated by Fern from our API Definition.

/** `pending` and `running` are in-progress; `succeeded` and `failed` are terminal. */
export const ProjectExportStatus = {
    Pending: "pending",
    Running: "running",
    Succeeded: "succeeded",
    Failed: "failed",
} as const;
export type ProjectExportStatus = (typeof ProjectExportStatus)[keyof typeof ProjectExportStatus];
