// This file was auto-generated by Fern from our API Definition.

import type * as VideoGenApi from "../index.js";

/**
 * Simplified project metadata.
 */
export interface ProjectResponse {
    projectId: string;
    title: string;
    aspectRatio: VideoGenApi.AspectRatio;
    /** High-level project status. */
    status: ProjectResponse.Status;
    createdAt: string;
    updatedAt: string;
    projectUrl: string;
}

export namespace ProjectResponse {
    /** High-level project status. */
    export const Status = {
        Generating: "generating",
        Ready: "ready",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
