// This file was auto-generated by Fern from our API Definition.

import type * as VideoGenApi from "../index.js";

export interface ProjectExport {
    /** Opaque export id (e.g. `vg_expo_...`) matching the original request. */
    exportId: string;
    /** Id of the exported project (e.g. `vg_proj_...`). */
    projectId: string;
    status: VideoGenApi.ProjectExportStatus;
    /** Completion progress for the current attempt (0-100). Always `100` when `status` is `succeeded`. */
    progressPercentage: number;
    /** Zero-based index of the current or most recent export attempt. */
    attemptIndex: number;
    /** Signed MP4 download URL. Present when `status` is `succeeded`. */
    downloadUrl?: (string | null) | undefined;
    /** Signed thumbnail URL. Present when `status` is `succeeded` and a thumbnail is available. */
    thumbnailUrl?: (string | null) | undefined;
    error?: (VideoGenApi.ApiError | null) | undefined;
}
