// This file was auto-generated by Fern from our API Definition.

import type * as VideoGenApi from "../index.js";

/**
 * A single edit applied to a project. Discriminated by `type`.
 */
export type RemixAction =
    | VideoGenApi.RemixAction.SetBackgroundMusic
    | VideoGenApi.RemixAction.SetLogo
    | VideoGenApi.RemixAction.EnableCaptions
    | VideoGenApi.RemixAction.DisableCaptions
    | VideoGenApi.RemixAction.VideoEditorAgent;

export namespace RemixAction {
    export interface SetBackgroundMusic extends VideoGenApi.RemixActionSetBackgroundMusic {
        type: "SET_BACKGROUND_MUSIC";
    }

    export interface SetLogo extends VideoGenApi.RemixActionSetLogo {
        type: "SET_LOGO";
    }

    export interface EnableCaptions extends VideoGenApi.RemixActionEnableCaptions {
        type: "ENABLE_CAPTIONS";
    }

    export interface DisableCaptions extends VideoGenApi.RemixActionDisableCaptions {
        type: "DISABLE_CAPTIONS";
    }

    export interface VideoEditorAgent extends VideoGenApi.RemixActionVideoEditorAgent {
        type: "VIDEO_EDITOR_AGENT";
    }
}
