// This file was auto-generated by Fern from our API Definition.

import type * as VideoGenApi from "../index.js";

/**
 * Change the project's output aspect ratio (e.g. to a vertical 9:16 social format). The video is re-flowed to the new ratio.
 */
export interface RemixActionResizeProject {
    aspectRatio: VideoGenApi.AspectRatio;
}
