// This file was auto-generated by Fern from our API Definition.

import type * as VideoGenApi from "../index.js";

export interface RemixActionRun {
    /** Opaque remix action id (e.g. `vg_rmix_...`). */
    remixActionId: string;
    type: VideoGenApi.RemixActionType;
    status: VideoGenApi.RemixActionStatus;
    /** Id of the project this remix action edits (e.g. `vg_proj_...`). */
    projectId: string;
    /** URL to view the project in the VideoGen app. */
    projectUrl: string;
    /** Completion progress for the current attempt (0-100). Always `100` when `status` is `succeeded`. */
    progressPercentage: number;
    /** Zero-based index of the current or most recent execution attempt. */
    attemptIndex: number;
    error?: (VideoGenApi.ApiError | null) | undefined;
}
