// This file was auto-generated by Fern from our API Definition.

import type * as VideoGenApi from "../index.js";

/**
 * Animate every eligible still image in the project into a short AI video clip (image-to-video), replacing each image in place. Eligible images are non-SVG image assets backed by an uploaded or stock file. Runs asynchronously: one clip is generated per image. If the project has no eligible images, the action is skipped and completes successfully without changing anything (for example, a project whose timeline is already all video clips).
 */
export interface RemixActionConvertImagesToVideos {
    /** Describe the motion to apply to every image (e.g. "slow cinematic push-in"). Omit or pass `null` for automatic motion. */
    motionPrompt?: (string | null) | undefined;
    /** Mute the generated clips and suppress generated background music. Recommended when the clips sit behind a voiceover. Defaults to `true`. */
    muteOutputVideos?: (boolean | null) | undefined;
    quality?: VideoGenApi.VideoQuality | undefined;
}
