// This file was auto-generated by Fern from our API Definition.

/** The kind of edit a remix action applies. */
export const RemixActionType = {
    SetBackgroundMusic: "SET_BACKGROUND_MUSIC",
    SetLogo: "SET_LOGO",
    EnableCaptions: "ENABLE_CAPTIONS",
    DisableCaptions: "DISABLE_CAPTIONS",
    VideoEditorAgent: "VIDEO_EDITOR_AGENT",
} as const;
export type RemixActionType = (typeof RemixActionType)[keyof typeof RemixActionType];
