// This file was auto-generated by Fern from our API Definition.

/** A transition applied at a boundary. `DYNAMIC` auto-varies the style across boundaries; `NONE` removes transitions; the rest apply that fixed style everywhere. */
export const RemixTransitionStyle = {
    Dynamic: "DYNAMIC",
    None: "NONE",
    Fade: "FADE",
    Rise: "RISE",
    Pan: "PAN",
    Pop: "POP",
    Wipe: "WIPE",
} as const;
export type RemixTransitionStyle = (typeof RemixTransitionStyle)[keyof typeof RemixTransitionStyle];
