// This file was auto-generated by Fern from our API Definition.

/**
 * Set, replace, or remove the logo overlay.
 */
export interface RemixActionSetLogo {
    /** File id of an uploaded image to overlay as a logo (e.g. `vg_file_...`). Upload it first via `POST /v1/files/upload`. Pass `null` to remove the existing logo. */
    fileId?: (string | null) | undefined;
    /** Position the logo is anchored to. Omit or pass `null` to keep the current position. */
    position?: (RemixActionSetLogo.Position | null) | undefined;
    /** Logo width as a percentage of the video width. Omit or pass `null` to keep the current size. */
    sizePercent?: (number | null) | undefined;
}

export namespace RemixActionSetLogo {
    /** Position the logo is anchored to. Omit or pass `null` to keep the current position. */
    export const Position = {
        TopLeft: "TOP_LEFT",
        TopCenter: "TOP_CENTER",
        TopRight: "TOP_RIGHT",
        BottomLeft: "BOTTOM_LEFT",
        BottomCenter: "BOTTOM_CENTER",
        BottomRight: "BOTTOM_RIGHT",
    } as const;
    export type Position = (typeof Position)[keyof typeof Position];
}
