// This file was auto-generated by Fern from our API Definition.

import type * as VideoGenApi from "../index.js";

/**
 * Show captions on every captionable section. Optionally override the project caption style.
 */
export interface RemixActionEnableCaptions {
    /** Caption styling to apply. Omit or pass `null` to show captions with the current style. Any provided field overrides that field; omitted fields keep their current value. */
    captionStyle?: (VideoGenApi.WorkflowCaptionStyle | null) | undefined;
}
