// This file was auto-generated by Fern from our API Definition.

/** Lifecycle status of a remix action. */
export const RemixActionStatus = {
    Pending: "pending",
    Running: "running",
    Succeeded: "succeeded",
    Failed: "failed",
    Cancelled: "cancelled",
} as const;
export type RemixActionStatus = (typeof RemixActionStatus)[keyof typeof RemixActionStatus];
