// This file was auto-generated by Fern from our API Definition.

import type * as VideoGenApi from "../index.js";

/**
 * A single edit applied to a project. Each array entry is exactly one of the six action types below, chosen by its `type` field; the variants are mutually-exclusive options, not fields you must all provide. Include only the actions you want.
 */
export type RemixAction =
    | VideoGenApi.RemixAction.SetBackgroundMusic
    | VideoGenApi.RemixAction.SetLogo
    | VideoGenApi.RemixAction.EnableCaptions
    | VideoGenApi.RemixAction.DisableCaptions
    | VideoGenApi.RemixAction.AddTransitions
    | VideoGenApi.RemixAction.EditWithAgent;

export namespace RemixAction {
    export interface SetBackgroundMusic extends VideoGenApi.RemixActionSetBackgroundMusic {
        type: "SET_BACKGROUND_MUSIC";
    }

    export interface SetLogo extends VideoGenApi.RemixActionSetLogo {
        type: "SET_LOGO";
    }

    export interface EnableCaptions extends VideoGenApi.RemixActionEnableCaptions {
        type: "ENABLE_CAPTIONS";
    }

    export interface DisableCaptions extends VideoGenApi.RemixActionDisableCaptions {
        type: "DISABLE_CAPTIONS";
    }

    export interface AddTransitions extends VideoGenApi.RemixActionAddTransitions {
        type: "ADD_TRANSITIONS";
    }

    export interface EditWithAgent extends VideoGenApi.RemixActionEditWithAgent {
        type: "EDIT_WITH_AGENT";
    }
}
