// This file was auto-generated by Fern from our API Definition.

/**
 * Replace every stock (library) visual in the project with a fresh alternative from the same search, replacing each in place. Runs asynchronously: each stock asset's original search is re-run, excluding the currently-shown result. If the project has no shuffleable stock visuals, the action is skipped and completes successfully without changing anything.
 */
export type RemixActionShuffleStockVisuals = {};
