// This file was auto-generated by Fern from our API Definition.

/**
 * Sharpen every eligible asset in the project up to 4K, replacing each in place. Runs asynchronously: one upscaled asset is generated per eligible asset. If the project has no eligible assets, the action is skipped and completes successfully without changing anything.
 */
export interface RemixActionUpscaleAssets {
    /** Also upscale video assets (billed per output second). Defaults to `true`. */
    includeVideos?: (boolean | null) | undefined;
    /** Also upscale stock (library) assets, not just uploaded or generated ones. Defaults to `true`. */
    includeStockContent?: (boolean | null) | undefined;
}
