// This file was auto-generated by Fern from our API Definition.

/**
 * Re-narrate every AI-voiceover asset in the project with a new voice (and optionally a presenter avatar), replacing each narration in place. Runs asynchronously: text-to-speech is re-fired per asset with the original narration text. If the project has no AI-narrated assets, the action is skipped and completes successfully without changing anything.
 */
export interface RemixActionChangeNarrator {
    /** Voice id from `GET /v1/resources/tts-voices` (e.g. `vg_voic_...`) to re-narrate with. */
    voiceId: string;
    /** Optional avatar presenter id from `GET /v1/resources/avatar-presenters` (e.g. `vg_pres_...`). When set, the narration is delivered by a talking-head presenter avatar. Pass your `voiceId` to that endpoint to list presenters sorted by best match for the voice. Omit or pass `null` for a standard voiceover with no presenter. */
    avatarPresenterId?: (string | null) | undefined;
    /** Speech rate multiplier. Omit or pass `null` to keep each asset's current speed. */
    voiceSpeed?: (number | null) | undefined;
}
