// This file was auto-generated by Fern from our API Definition.

/**
 * Set, replace, or remove the project's background music track.
 */
export interface RemixActionSetBackgroundMusic {
    /** File id of an uploaded audio file to use as background music (e.g. `vg_file_...`). Upload it first via `POST /v1/files/upload`. Pass `null` to remove the existing background music. */
    fileId?: (string | null) | undefined;
    /** Music volume from 0 (silent) to 1 (full). Omit or pass `null` to keep the current volume. */
    volume?: (number | null) | undefined;
}
