// This file was auto-generated by Fern from our API Definition.

import type * as VideoGenApi from "../index.js";

/**
 * A single edit applied to a project. Each array entry is exactly one of the action types below, chosen by its `type` field; the variants are mutually-exclusive options, not fields you must all provide. Include only the actions you want.
 */
export type RemixAction =
    | VideoGenApi.RemixAction.SetBackgroundMusic
    | VideoGenApi.RemixAction.SetLogo
    | VideoGenApi.RemixAction.EnableCaptions
    | VideoGenApi.RemixAction.DisableCaptions
    | VideoGenApi.RemixAction.AddTransitions
    | VideoGenApi.RemixAction.ResizeProject
    | VideoGenApi.RemixAction.CleanUpTranscript
    | VideoGenApi.RemixAction.ConvertImagesToVideos
    | VideoGenApi.RemixAction.RegenerateImages
    | VideoGenApi.RemixAction.UpscaleAssets
    | VideoGenApi.RemixAction.ChangeNarrator
    | VideoGenApi.RemixAction.ShuffleStockVisuals
    | VideoGenApi.RemixAction.GenerateMusic
    | VideoGenApi.RemixAction.TranslateProject
    | VideoGenApi.RemixAction.EditWithAgent;

export namespace RemixAction {
    export interface SetBackgroundMusic extends VideoGenApi.RemixActionSetBackgroundMusic {
        type: "SET_BACKGROUND_MUSIC";
    }

    export interface SetLogo extends VideoGenApi.RemixActionSetLogo {
        type: "SET_LOGO";
    }

    export interface EnableCaptions extends VideoGenApi.RemixActionEnableCaptions {
        type: "ENABLE_CAPTIONS";
    }

    export interface DisableCaptions extends VideoGenApi.RemixActionDisableCaptions {
        type: "DISABLE_CAPTIONS";
    }

    export interface AddTransitions extends VideoGenApi.RemixActionAddTransitions {
        type: "ADD_TRANSITIONS";
    }

    export interface ResizeProject extends VideoGenApi.RemixActionResizeProject {
        type: "RESIZE_PROJECT";
    }

    export interface CleanUpTranscript extends VideoGenApi.RemixActionCleanUpTranscript {
        type: "CLEAN_UP_TRANSCRIPT";
    }

    export interface ConvertImagesToVideos extends VideoGenApi.RemixActionConvertImagesToVideos {
        type: "CONVERT_IMAGES_TO_VIDEOS";
    }

    export interface RegenerateImages extends VideoGenApi.RemixActionRegenerateImages {
        type: "REGENERATE_IMAGES";
    }

    export interface UpscaleAssets extends VideoGenApi.RemixActionUpscaleAssets {
        type: "UPSCALE_ASSETS";
    }

    export interface ChangeNarrator extends VideoGenApi.RemixActionChangeNarrator {
        type: "CHANGE_NARRATOR";
    }

    export interface ShuffleStockVisuals extends VideoGenApi.RemixActionShuffleStockVisuals {
        type: "SHUFFLE_STOCK_VISUALS";
    }

    export interface GenerateMusic extends VideoGenApi.RemixActionGenerateMusic {
        type: "GENERATE_MUSIC";
    }

    export interface TranslateProject extends VideoGenApi.RemixActionTranslateProject {
        type: "TRANSLATE_PROJECT";
    }

    export interface EditWithAgent extends VideoGenApi.RemixActionEditWithAgent {
        type: "EDIT_WITH_AGENT";
    }
}
