// This file was auto-generated by Fern from our API Definition.

/**
 * Generate a background music track from a text prompt and set it as the project's background music, replacing any existing track. Runs asynchronously.
 */
export interface RemixActionGenerateMusic {
    /** Describe the music to generate (e.g. "upbeat corporate background music with a driving beat"). */
    prompt: string;
}
