// This file was auto-generated by Fern from our API Definition.

/**
 * How a scene is generated. Tagged by `type`: AI_IMAGE produces a still image from the prompt; AI_VIDEO produces a video clip from the prompt.
 */
export interface SceneGeneration {
    /** AI_IMAGE generates a still image. AI_VIDEO generates a video clip. */
    type: SceneGeneration.Type;
    /** Either a style id from the AI styles reference (e.g. `WATERCOLOR`) or free-form text describing a custom style, appended to the scene prompt. No extra style is applied when omitted. */
    style?: (string | null) | undefined;
}

export namespace SceneGeneration {
    /** AI_IMAGE generates a still image. AI_VIDEO generates a video clip. */
    export const Type = {
        AiImage: "AI_IMAGE",
        AiVideo: "AI_VIDEO",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
