// This file was auto-generated by Fern from our API Definition.

import type * as VideoGenApi from "../index.js";

export interface ScriptToVideoRequest {
    /** The narration script, used verbatim. This exact text is narrated and turned into a video — it is not rewritten or expanded. */
    script: string;
    aspectRatio?: VideoGenApi.AspectRatio | undefined;
    visualStyle: VideoGenApi.WorkflowVisualStyle;
    visualPacing?: VideoGenApi.VisualPacing | undefined;
    /** Image generation quality tier for AI-generated visuals. LOW is fastest and cheapest; STANDARD balances quality and cost; HIGH is highest quality. Only applies when `visualStyle.type` is AI_IMAGE or ENTITY; STOCK pulls existing footage and is unaffected. Defaults to STANDARD. */
    quality?: ScriptToVideoRequest.Quality | undefined;
    /** Output language as a BCP-47 code (e.g. `en`, `es`, `fr`). Defaults to English. */
    language?: string | undefined;
    /** Voice id from `GET /v1/resources/tts-voices` (e.g. `vg_voic_...`). A default voice is used when omitted. Any voice may be used here, including voices where `supportsDirectToolExecution` is false. */
    voiceId?: (string | null) | undefined;
    /** Speech rate multiplier. Defaults to the voice's default speed. */
    voiceSpeed?: number | undefined;
    /** Optional avatar presenter id from `GET /v1/resources/avatar-presenters` (e.g. `vg_pres_...`). When set, the narration is delivered by a talking-head presenter avatar. Pass your `voiceId` to that endpoint to list presenters sorted by best match for the voice. Omit for a standard voiceover with no presenter. */
    avatarPresenterId?: (string | null) | undefined;
    /** Optional file ids of images or videos to feature as b-roll (e.g. `["vg_file_..."]`). Upload files first via `POST /v1/files/upload`. Only image and video files are accepted. */
    featuredBRollFileIds?: string[] | undefined;
    /** Optional production notes for the AI that builds the video — visual direction that should not appear in the spoken narration (e.g. on-screen code or text to display, specific b-roll to feature, or scene-by-scene staging). Never spoken; keep the narration itself in `script`. */
    workflowAgentContext?: string | undefined;
    /** Optional edits applied to the project after the video is built, in order. Each action runs asynchronously; the response returns one remix action id per action. Recommended for script-to-video: `ENABLE_CAPTIONS` to show and style captions, `CONVERT_IMAGES_TO_VIDEOS` to animate still images into clips, `ADD_TRANSITIONS` to stamp transitions between sections, and `SET_LOGO` to overlay a logo (this workflow has no native caption-style or logo fields). `EDIT_WITH_AGENT` applies open-ended natural-language edits. See the [Remix actions](/remix-actions) guide. */
    remixActions?: VideoGenApi.RemixAction[] | undefined;
}

export namespace ScriptToVideoRequest {
    /** Image generation quality tier for AI-generated visuals. LOW is fastest and cheapest; STANDARD balances quality and cost; HIGH is highest quality. Only applies when `visualStyle.type` is AI_IMAGE or ENTITY; STOCK pulls existing footage and is unaffected. Defaults to STANDARD. */
    export const Quality = {
        Low: "LOW",
        Standard: "STANDARD",
        High: "HIGH",
    } as const;
    export type Quality = (typeof Quality)[keyof typeof Quality];
}
