// This file was auto-generated by Fern from our API Definition.

/**
 * Identifier for the in-flight tool execution. Pass `apiTaskExecutionId` back when polling, cancelling, or correlating webhook events.
 */
export interface StartToolExecutionResponse {
    /** Opaque execution id (`api-t<taskId>-e<taskExecutionId>`). Treat as a single string — do not split it client-side. */
    apiTaskExecutionId: string;
}
