// This file was auto-generated by Fern from our API Definition.

/**
 * Returned when a workflow run is accepted. Poll `GET /v1/workflows/runs/{workflowRunId}` or subscribe to webhooks for completion.
 */
export interface StartWorkflowRunResponse {
    /** Opaque workflow run id (e.g. `vg_work_...`). */
    workflowRunId: string;
    /** Id of the project created for this workflow run (e.g. `vg_proj_...`). */
    projectId: string;
    /** URL to view the project in the VideoGen app. */
    projectUrl: string;
    /** Opaque remix action ids (e.g. `vg_rmix_...`), one per `remixActions` entry in request order. Empty when no remix actions were requested. Each runs after the video is built; poll `GET /v1/projects/{projectId}/remix-actions`. */
    remixActionIds: string[];
}
