// This file was auto-generated by Fern from our API Definition.

/**
 * Returned when a workflow run is accepted. Poll `GET /v1/workflows/runs/{workflowRunId}` or subscribe to webhooks for completion.
 */
export interface StartWorkflowRunResponse {
    /** Opaque workflow run id (e.g. `vg_work_...`). */
    workflowRunId: string;
    /** Id of the project created for this workflow run (e.g. `vg_proj_...`). */
    projectId: string;
    /** Deep link to open this project in the VideoGen web editor. Not required for an API-only integration: store `projectId` and use the Projects API (export, remix, metadata). Use `projectUrl` when a person should open the project in the app to review or edit it manually. The project is visible only to members of your team and any project collaborators, the same access model as a project created in the dashboard. */
    projectUrl: string;
    /** Opaque remix action ids (e.g. `vg_rmix_...`), one per `remixActions` entry in request order. Empty when no remix actions were requested. Each runs after the video is built; poll `GET /v1/projects/{projectId}/remix-actions`. */
    remixActionIds: string[];
}
