// This file was auto-generated by Fern from our API Definition.

/**
 * The tool run was accepted. Use `apiTaskExecutionId` when polling, canceling, or matching webhook deliveries.
 */
export interface StartToolExecutionResponse {
    /** Execution id for this run. */
    apiTaskExecutionId: string;
}
