// This file was auto-generated by Fern from our API Definition.

/**
 * Metadata for a file in your workspace. Obtain ids from tool results or `GET /v1/files`.
 */
export interface StorageFile {
    /** Primary identifier for the file in workspace storage. */
    storageFileId: string;
    /** Asset kind. */
    type: StorageFile.Type;
    /** Optional; server may default when omitted. */
    displayName?: string | undefined;
    description?: (string | null) | undefined;
}

export namespace StorageFile {
    /** Asset kind. */
    export const Type = {
        Image: "IMAGE",
        Video: "VIDEO",
        Audio: "AUDIO",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
