// This file was auto-generated by Fern from our API Definition.

/**
 * Workspace storage file metadata (no internal `_v_*` stamps).
 * Use `storageFileId` from upload or `getFile` / `getFiles`.
 */
export interface StorageFile {
    /** Primary identifier for the file in workspace storage. */
    storageFileId: string;
    /** Same enum as `StorageFileType` in the app. */
    type: StorageFile.Type;
    /** Optional; server may default when omitted. */
    displayName?: string | undefined;
    description?: (string | null) | undefined;
}

export namespace StorageFile {
    /** Same enum as `StorageFileType` in the app. */
    export const Type = {
        Image: "IMAGE",
        Video: "VIDEO",
        Audio: "AUDIO",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
