// This file was auto-generated by Fern from our API Definition.

/**
 * Metadata for a file in your workspace. Obtain ids from tool results or `GET /v1/files`.
 */
export interface StorageFile {
    /** Opaque file id (e.g. `vg_file_...`). Pass it back in `StorageFileRef` fields and `GET /v1/files/{storageFileId}` requests. */
    storageFileId: string;
    /** Asset kind. */
    type: StorageFile.Type;
    /** Storage scope of the file. `GLOBAL` files persist in the workspace, `TEMPORARY` files are auto-cleaned. */
    scope: StorageFile.Scope;
    /** Optional; server may default when omitted. */
    displayName?: string | undefined;
    description?: (string | null) | undefined;
}

export namespace StorageFile {
    /** Asset kind. */
    export const Type = {
        Image: "IMAGE",
        Video: "VIDEO",
        Audio: "AUDIO",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
    /** Storage scope of the file. `GLOBAL` files persist in the workspace, `TEMPORARY` files are auto-cleaned. */
    export const Scope = {
        Global: "GLOBAL",
        Project: "PROJECT",
        Export: "EXPORT",
        Temporary: "TEMPORARY",
    } as const;
    export type Scope = (typeof Scope)[keyof typeof Scope];
}
