// This file was auto-generated by Fern from our API Definition.

/**
 * Reference to an existing file by id and type. Pass this in tool request bodies.
 */
export interface StorageFileRef {
    /** File id (e.g. `vg_file_...`) from a tool result or `GET /v1/files`. */
    storageFileId: string;
    /** Must match the file's type. */
    type: StorageFileRef.Type;
}

export namespace StorageFileRef {
    /** Must match the file's type. */
    export const Type = {
        Image: "IMAGE",
        Video: "VIDEO",
        Audio: "AUDIO",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
