// This file was auto-generated by Fern from our API Definition.

import type * as VideogenApi from "../index.js";

/**
 * Body POSTed to a registered webhook endpoint when a tool execution reaches a terminal state. Use `apiTaskExecutionId` to correlate with the response from `POST /v1/tools/...`. The `result` and `error` fields are only populated on `tool_execution.succeeded`; for failure or cancellation reasons, fetch `GET /v1/tools/executions/{apiTaskExecutionId}` to retrieve the full `ExecutedTool` (including `error.message` for failures).
 */
export interface ToolExecutionWebhookPayload {
    event: VideogenApi.ToolExecutionWebhookEventName;
    /** Same opaque execution id returned from `POST /v1/tools/...`. */
    apiTaskExecutionId: string;
    /** ISO-8601 timestamp at which VideoGen observed the terminal state. */
    occurredAt: string;
    /** Logical tool name (e.g. PROMPT_TO_IMAGE, PROMPT_TO_VIDEO_CLIP). */
    toolType: string;
    /** Present only on `tool_execution.succeeded`. Same shape as `ExecutedTool.result`. For `tool_execution.failed` and `tool_execution.cancelled`, fetch `GET /v1/tools/executions/{apiTaskExecutionId}` for details. */
    result?: VideogenApi.ToolSuccessResult | undefined;
}
