// This file was auto-generated by Fern from our API Definition.

/** Webhook event types for tool execution lifecycle. */
export const ToolExecutionWebhookEventName = {
    ToolExecutionSucceeded: "tool_execution.succeeded",
    ToolExecutionFailed: "tool_execution.failed",
    ToolExecutionCancelled: "tool_execution.cancelled",
} as const;
export type ToolExecutionWebhookEventName =
    (typeof ToolExecutionWebhookEventName)[keyof typeof ToolExecutionWebhookEventName];
