// This file was auto-generated by Fern from our API Definition.

import type * as VideogenApi from "../index.js";

/**
 * Body POSTed to a registered webhook endpoint when a tool execution reaches a terminal state. Use `apiTaskExecutionId` to correlate with the response from `POST /v1/tools/...`. For full error details on failed runs, fetch `GET /v1/tools/executions/{apiTaskExecutionId}`.
 */
export interface ToolExecutionWebhookPayload {
    event: VideogenApi.ToolExecutionWebhookEventName;
    /** Same opaque execution id returned from `POST /v1/tools/...`. */
    apiTaskExecutionId: string;
    /** ISO-8601 timestamp at which VideoGen observed the terminal state. */
    occurredAt: string;
    /** Logical tool name (e.g. GENERATE_IMAGE, GENERATE_VIDEO_CLIP). */
    toolType: string;
    /** Present only on `tool_execution.succeeded`. Same shape as `ExecutedTool.result`. */
    result?: VideogenApi.ToolSuccessResult | undefined;
}
