// This file was auto-generated by Fern from our API Definition.

/**
 * Tool-specific payload when `status` is `succeeded`. Typical keys include `imageUrl`, `videoUrl`,
 * `fileId`, or `assets`—concrete fields depend on the tool that ran (`toolType`).
 */
export type ToolSuccessResult = Record<string, unknown>;
