// This file was auto-generated by Fern from our API Definition.

/**
 * Present when `status` is `succeeded`. Contains `storageFileId` and `type` for the generated file.
 */
export interface ToolSuccessResult {
    /** File id for the generated asset. */
    storageFileId?: string | undefined;
    /** File type. */
    type?: ToolSuccessResult.Type | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}

export namespace ToolSuccessResult {
    /** File type. */
    export const Type = {
        Image: "IMAGE",
        Video: "VIDEO",
        Audio: "AUDIO",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
