// This file was auto-generated by Fern from our API Definition.

import type * as VideogenApi from "../index.js";

/**
 * Present when `status` is `succeeded` and the tool produced file output(s).
 */
export interface ToolSuccessResult {
    /** One entry per output file, in order. */
    files: VideogenApi.StorageFile[];
    /** Accepts any additional properties */
    [key: string]: any;
}
