// This file was auto-generated by Fern from our API Definition.

import type * as VideoGenApi from "../index.js";

/**
 * Delivered to your webhook endpoint when a tool execution reaches a terminal state. The shape mirrors the `ExecutedTool` response with the addition of `event` and `occurredAt`.
 */
export interface ToolExecutionWebhookPayload {
    event: VideoGenApi.ToolExecutionWebhookEventName;
    /** Execution id matching the original request. */
    toolExecutionId: string;
    /** Seconds since epoch (Unix timestamp) when the execution reached a terminal state. */
    occurredAt: number;
    /** Tool name (e.g. `GENERATE_IMAGE`, `TEXT_TO_SPEECH`). */
    toolType: string;
    /** One entry per generated result, each with a hydrated `file`. Present only on `tool_execution.succeeded`. */
    results?: VideoGenApi.ToolSuccessResult[] | undefined;
    /** Present only on `tool_execution.failed`. */
    error?: VideoGenApi.ApiError | undefined;
}
