// This file was auto-generated by Fern from our API Definition.

/**
 * A TTS voice you can pass to `POST /v1/tools/generate-tts` via `voiceId`.
 */
export interface TtsVoice {
    /** Pass as `voiceId` in `POST /v1/tools/generate-tts`. */
    voiceId: string;
    /** Underlying TTS provider that powers this voice (e.g. `ELEVEN_LABS`, `GOOGLE`). */
    providerName: string;
    /** Locale tag for the voice (e.g. `en-US`, `es-ES`). */
    languageCode: string;
    /** Human-readable voice name. */
    displayName: string;
    /** Voice gender as it should be displayed. */
    displayGender: TtsVoice.DisplayGender;
    /** Optional accent label (e.g. `american`, `british`). */
    accent?: (string | null) | undefined;
    /** Free-form description of the voice's character. */
    description?: (string | null) | undefined;
}

export namespace TtsVoice {
    /** Voice gender as it should be displayed. */
    export const DisplayGender = {
        Male: "MALE",
        Female: "FEMALE",
        Neutral: "NEUTRAL",
    } as const;
    export type DisplayGender = (typeof DisplayGender)[keyof typeof DisplayGender];
}
