// This file was auto-generated by Fern from our API Definition.

/**
 * A text-to-speech voice.
 */
export interface TtsVoice {
    /** Voice id (e.g. `vg_voic_...`). Pass as `voiceId` to `POST /v1/tools/text-to-speech`. */
    voiceId: string;
    /** Locale tag for the voice (e.g. `en-US`, `es-ES`). */
    languageCode: string;
    /** Human-readable voice name. */
    displayName: string;
    /** Voice gender. */
    displayGender: TtsVoice.DisplayGender;
    /** Accent (e.g. `american`, `british`). */
    accent?: (string | null) | undefined;
    /** Description of the voice. */
    description?: (string | null) | undefined;
    /** When true, this voice can be used directly with `POST /v1/tools/text-to-speech`. Voices where this is false are returned for discovery purposes but cannot be used through this API. */
    supportsDirectToolExecution: boolean;
    /** When true, this voice can synthesize text in any language regardless of its `languageCode`. When false, the voice only supports its listed language. */
    supportsAllLanguages: boolean;
    /** When true, this voice is deprecated and may be removed in a future API version. Prefer non-deprecated voices for new integrations. */
    isDeprecated: boolean;
}

export namespace TtsVoice {
    /** Voice gender. */
    export const DisplayGender = {
        Male: "MALE",
        Female: "FEMALE",
        Neutral: "NEUTRAL",
    } as const;
    export type DisplayGender = (typeof DisplayGender)[keyof typeof DisplayGender];
}
