// This file was auto-generated by Fern from our API Definition.

/** Video generation quality tier. */
export const VideoModelMode = {
    Standard: "STANDARD",
    High: "HIGH",
} as const;
export type VideoModelMode = (typeof VideoModelMode)[keyof typeof VideoModelMode];
