// This file was auto-generated by Fern from our API Definition.

/** Controls whether the VideoGen watermark is applied to the output. `AUTO` applies the watermark unless you have the Production API add-on. `VIDEO_GEN` always applies it. `NONE` removes the watermark — requires the Production API add-on; returns an error if you don't have it. */
export const WatermarkMode = {
    None: "NONE",
    VideoGen: "VIDEO_GEN",
    Auto: "AUTO",
} as const;
export type WatermarkMode = (typeof WatermarkMode)[keyof typeof WatermarkMode];
