// This file was auto-generated by Fern from our API Definition.

import type * as VideoGenApi from "../index.js";

export interface WebhookEndpoint {
    endpointId: string;
    url: string;
    events: VideoGenApi.ToolExecutionWebhookEventName[];
    description?: (string | null) | undefined;
    /** Seconds since epoch (Unix timestamp) when the endpoint was created. */
    createdAt: number;
    /** HMAC secret for verifying [Standard Webhooks](https://www.standardwebhooks.com/) signatures. **Only returned once** on create — store it securely. */
    signingSecret?: string | undefined;
    /** Last four characters of the signing secret, for display purposes. */
    signingSecretLast4?: string | undefined;
}
