// This file was auto-generated by Fern from our API Definition.

import type * as VideogenApi from "../index.js";

export interface WebhookEndpoint {
    endpointId: string;
    url: string;
    events: VideogenApi.ToolExecutionWebhookEventName[];
    description?: (string | null) | undefined;
    createdAt: string;
    /**
     * Only present on create (`201`) response. Store securely; used to verify `X-VideoGen-Signature`.
     * Never returned on list.
     */
    signingSecret?: string | undefined;
    /** Last four characters of the signing secret (for display); omitted if not yet provisioned. */
    signingSecretLast4?: string | undefined;
}
