// This file was auto-generated by Fern from our API Definition.

import type * as VideogenApi from "../index.js";

export interface WebhookEndpoint {
    endpointId: string;
    url: string;
    events: VideogenApi.ToolExecutionWebhookEventName[];
    description?: (string | null) | undefined;
    createdAt: string;
    /** HMAC secret used to verify Standard Webhooks signatures. **Returned only on the create response**; subsequent list/get calls omit it. Store it securely — it cannot be retrieved again. */
    signingSecret?: string | undefined;
    /** Last four characters of the signing secret (for display in the developer dashboard); omitted if not yet provisioned. */
    signingSecretLast4?: string | undefined;
}
