// This file was auto-generated by Fern from our API Definition.

import type * as VideoGenApi from "../index.js";

export interface WorkflowRun {
    /** Opaque workflow run id. */
    workflowRunId: string;
    status: VideoGenApi.WorkflowRunStatus;
    workflowType: VideoGenApi.WorkflowType;
    /** Completion progress for the current attempt (0-100). Always `100` when `status` is `succeeded`. */
    progressPercentage: number;
    /** Zero-based index of the current or most recent execution attempt. */
    attemptIndex: number;
    /** Id of the project created for this workflow run (e.g. `vg_proj_...`). */
    projectId: string;
    /** Deep link to open this project in the VideoGen web editor. Not required for an API-only integration: store `projectId` and use the Projects API (export, remix, metadata). Use `projectUrl` when a person should open the project in the app to review or edit it manually. The project is visible only to members of your team and any project collaborators, the same access model as a project created in the dashboard. */
    projectUrl: string;
    error?: (VideoGenApi.ApiError | null) | undefined;
}
