// This file was auto-generated by Fern from our API Definition.

/** Lifecycle status of a workflow run. */
export const WorkflowRunStatus = {
    Pending: "pending",
    Running: "running",
    Succeeded: "succeeded",
    Failed: "failed",
    Cancelled: "cancelled",
} as const;
export type WorkflowRunStatus = (typeof WorkflowRunStatus)[keyof typeof WorkflowRunStatus];
