// This file was auto-generated by Fern from our API Definition.

import type * as VideoGenApi from "../index.js";

/**
 * Paginated list of API-started workflow runs, most recently created first.
 */
export interface WorkflowRunListResponse {
    workflowRuns: VideoGenApi.WorkflowRun[];
    /** When true, there are more runs available. Pass `nextCursor` as the `cursor` query param to fetch the next page. */
    hasMore: boolean;
    /** Opaque cursor to fetch the next page. `null` when `hasMore` is false. */
    nextCursor: string | null;
}
