// This file was auto-generated by Fern from our API Definition.

import type * as VideoGenApi from "../index.js";

/**
 * Background drawn behind caption text.
 */
export interface WorkflowCaptionBackgroundStyle {
    /** RECT draws one rectangle behind the whole line; WRAPPED hugs the text; WORD_BY_WORD draws a box per word. */
    type: WorkflowCaptionBackgroundStyle.Type;
    backgroundColor: VideoGenApi.WorkflowRgbColor;
    /** Corner rounding as a proportion of the background height (0 = square corners). */
    borderRadiusProportion?: number | undefined;
    /** Background opacity from 0 (transparent) to 1 (opaque). */
    opacityProportion?: number | undefined;
}

export namespace WorkflowCaptionBackgroundStyle {
    /** RECT draws one rectangle behind the whole line; WRAPPED hugs the text; WORD_BY_WORD draws a box per word. */
    export const Type = {
        Rect: "RECT",
        Wrapped: "WRAPPED",
        WordByWord: "WORD_BY_WORD",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
