// This file was auto-generated by Fern from our API Definition.

import type * as VideoGenApi from "../index.js";

/**
 * Body POSTed to a registered webhook endpoint when a workflow run reaches a terminal state.
 */
export interface WorkflowRunWebhookPayload {
    event: VideoGenApi.WorkflowRunWebhookEventName;
    /** Opaque workflow run id matching the original request. */
    workflowRunId: string;
    /** ISO-8601 timestamp at which VideoGen observed the terminal state. */
    occurredAt: string;
    workflowType: VideoGenApi.WorkflowType;
    /** Id of the project created for this workflow run (e.g. `vg_proj_...`). */
    projectId: string;
    /** Deep link to open this project in the VideoGen web editor. Not required for an API-only integration: store `projectId` and use the Projects API (export, remix, metadata). Use `projectUrl` when a person should open the project in the app to review or edit it manually. The project is visible only to members of your team and any project collaborators, the same access model as a project created in the dashboard. */
    projectUrl: string;
    /** Present only on `workflow_run.failed`. */
    error?: VideoGenApi.ApiError | undefined;
}
