// This file was auto-generated by Fern from our API Definition.

/** Workflow type identifier. */
export const WorkflowType = {
    ScriptToVideo: "SCRIPT_TO_VIDEO",
    VoiceoverToVideo: "VOICEOVER_TO_VIDEO",
    SlideshowToVideo: "SLIDESHOW_TO_VIDEO",
    StoryboardToVideo: "STORYBOARD_TO_VIDEO",
} as const;
export type WorkflowType = (typeof WorkflowType)[keyof typeof WorkflowType];
