// This file was auto-generated by Fern from our API Definition.

/** Lifecycle events emitted for workflow runs started via the developer API. */
export const WorkflowRunWebhookEventName = {
    WorkflowRunSucceeded: "workflow_run.succeeded",
    WorkflowRunFailed: "workflow_run.failed",
    WorkflowRunCancelled: "workflow_run.cancelled",
} as const;
export type WorkflowRunWebhookEventName =
    (typeof WorkflowRunWebhookEventName)[keyof typeof WorkflowRunWebhookEventName];
