// This file was auto-generated by Fern from our API Definition.

/**
 * Visual treatment for the generated b-roll.
 */
export interface WorkflowVisualStyle {
    /** STOCK pulls stock footage and images. AI_IMAGE generates a styled image for each section. ENTITY generates images that match a visual-style entity's reference images for a consistent look. */
    type: WorkflowVisualStyle.Type;
    /** Only applies when type is AI_IMAGE. A free-form description of the look applied to every generated image (e.g. `vintage 1970s film photography, warm grain`). See the AI styles reference for example descriptions of the app's default styles. Required when type is AI_IMAGE. */
    aiStyle?: string | undefined;
    /** Only applies when type is ENTITY. The id of a VISUAL_STYLE entity (e.g. `vg_enti_...`) whose reference images guide every generated image. Required when type is ENTITY. */
    entityId?: string | undefined;
    /** Only applies when type is AI_IMAGE. When true, featured b-roll images you provide are re-rendered in the chosen style so they match the generated look (no effect on featured b-roll videos). Defaults to true. */
    restyleFeaturedBRollWithAiStyle?: boolean | undefined;
}

export namespace WorkflowVisualStyle {
    /** STOCK pulls stock footage and images. AI_IMAGE generates a styled image for each section. ENTITY generates images that match a visual-style entity's reference images for a consistent look. */
    export const Type = {
        Stock: "STOCK",
        AiImage: "AI_IMAGE",
        Entity: "ENTITY",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
