// This file was auto-generated by Fern from our API Definition.

/**
 * An RGB color. Each channel is an integer from 0 to 255.
 */
export interface WorkflowRgbColor {
    red: number;
    green: number;
    blue: number;
}
