// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         projectId: "projectId",
 *         message: "Make it more upbeat and add captions"
 *     }
 */
export interface SendAssistantMessageRequest {
    /** The project id (e.g. `vg_proj_...`). */
    projectId: string;
    /** The message to send to the assistant in this project chat. */
    message: string;
}
