// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         type: "IMAGE",
 *         displayName: "displayName"
 *     }
 */
export interface CreateFileUploadRequest {
    /** The type of file to upload. */
    type: CreateFileUploadRequest.Type;
    /** Display name for the uploaded file. */
    displayName: string;
    /** When true, the file is temporary and automatically deleted after 24 hours. Defaults to false. */
    isTemporary?: boolean;
}

export namespace CreateFileUploadRequest {
    /** The type of file to upload. */
    export const Type = {
        Image: "IMAGE",
        Video: "VIDEO",
        Audio: "AUDIO",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
