// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         fileId: "fileId"
 *     }
 */
export interface DisablePublicPreviewRequest {
    fileId: string;
}
