// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         storageFileId: "storageFileId"
 *     }
 */
export interface DisablePublicPreviewRequest {
    storageFileId: string;
}
