// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         fileId: "vg_file_obLD1OX2eJCrEs0071Z4kA"
 *     }
 */
export interface EnablePublicPreviewRequest {
    /** The file id (e.g. `vg_file_...`). */
    fileId: string;
}
