// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         query: "query"
 *     }
 */
export interface SearchFilesRequest {
    /** Natural-language search query. The text is embedded and compared against file description vectors using cosine similarity. */
    query: string;
    /** Number of results to return (1-100). Defaults to 10. */
    numResults?: number;
    /** When true, only files created by the calling API key's user are returned. When false (default), all files accessible to the team are included. */
    selfOnly?: boolean;
}
