// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "name"
 *     }
 */
export interface CreatePetRequest {
    /** Name of the pet. */
    name: string;
    /** Optional tag for the pet. */
    tag?: string;
}
