// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         petId: "petId"
 *     }
 */
export interface GetPetRequest {
    /** The ID of the pet to retrieve. */
    petId: string;
}
