// This file was auto-generated by Fern from our API Definition.

import { VideoGenClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("AccountClient", () => {
    test("getMe", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            apiKeyId: "7c9e6a2b-1d3f-4a58-9b0c-2e4f6a8c1d02",
            apiKeyNickname: "Production key",
            email: "developer@example.com",
            displayName: "Ada Lovelace",
            teamId: "1f0a2b3c-4d5e-6789-ab12-cdef34567890",
        };

        server.mockEndpoint().get("/v1/me").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.account.getMe();
        expect(response).toEqual(rawResponseBody);
    });
});
