// This file was auto-generated by Fern from our API Definition.

import { VideoGenClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("EntitiesClient", () => {
    test("listEntities", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            entities: [
                {
                    entityId: "entityId",
                    entityType: "ACTOR",
                    name: "name",
                    description: "description",
                    actorConfig: { hasVoice: true, hasAvatarPresenter: true },
                    references: [{ fileId: "fileId", description: "description", isDefault: true }],
                    createdAt: "2024-01-15T09:30:00Z",
                    updatedAt: "2024-01-15T09:30:00Z",
                },
            ],
            hasMore: true,
            nextCursor: "nextCursor",
        };

        server.mockEndpoint().get("/v1/entities").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.entities.listEntities();
        expect(response).toEqual(rawResponseBody);
    });

    test("createEntity", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { entityType: "ACTOR", name: "name" };
        const rawResponseBody = {
            entityId: "entityId",
            entityType: "ACTOR",
            name: "name",
            description: "description",
            actorConfig: { voiceDisplayName: "voiceDisplayName", hasVoice: true, hasAvatarPresenter: true },
            references: [{ fileId: "fileId", description: "description", isDefault: true }],
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/v1/entities")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.entities.createEntity({
            entityType: "ACTOR",
            name: "name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getEntity", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            entityId: "entityId",
            entityType: "ACTOR",
            name: "name",
            description: "description",
            actorConfig: { voiceDisplayName: "voiceDisplayName", hasVoice: true, hasAvatarPresenter: true },
            references: [{ fileId: "fileId", description: "description", isDefault: true }],
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .get("/v1/entities/entityId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.entities.getEntity({
            entityId: "entityId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("updateEntity", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            entityId: "entityId",
            entityType: "ACTOR",
            name: "name",
            description: "description",
            actorConfig: { voiceDisplayName: "voiceDisplayName", hasVoice: true, hasAvatarPresenter: true },
            references: [{ fileId: "fileId", description: "description", isDefault: true }],
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/v1/entities/entityId/update")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.entities.updateEntity({
            entityId: "entityId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("archiveEntity", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { entityId: "entityId", archived: true };

        server
            .mockEndpoint()
            .post("/v1/entities/entityId/archive")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.entities.archiveEntity({
            entityId: "entityId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("addEntityReference", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { fileId: "fileId" };
        const rawResponseBody = {
            entityId: "entityId",
            entityType: "ACTOR",
            name: "name",
            description: "description",
            actorConfig: { voiceDisplayName: "voiceDisplayName", hasVoice: true, hasAvatarPresenter: true },
            references: [{ fileId: "fileId", description: "description", isDefault: true }],
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/v1/entities/entityId/references")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.entities.addEntityReference({
            entityId: "entityId",
            fileId: "fileId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("removeEntityReference", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { fileId: "fileId" };
        const rawResponseBody = {
            entityId: "entityId",
            entityType: "ACTOR",
            name: "name",
            description: "description",
            actorConfig: { voiceDisplayName: "voiceDisplayName", hasVoice: true, hasAvatarPresenter: true },
            references: [{ fileId: "fileId", description: "description", isDefault: true }],
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/v1/entities/entityId/references/remove")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.entities.removeEntityReference({
            entityId: "entityId",
            fileId: "fileId",
        });
        expect(response).toEqual(rawResponseBody);
    });
});
