// This file was auto-generated by Fern from our API Definition.

import { VideoGenClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("EntitiesClient", () => {
    test("listEntities", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            entities: [
                {
                    entityId: "vg_enti_a1b2c3d4e5f6",
                    entityType: "ACTOR",
                    name: "Maya the host",
                    description: "Friendly on-camera host for product explainers.",
                    actorConfig: { voiceDisplayName: "Matilda", hasVoice: true, hasAvatarPresenter: true },
                    references: [
                        {
                            fileId: "vg_file_obLD1OX2eJCrEs0071Z4kA",
                            description: "Front-facing headshot, neutral background.",
                            isDefault: true,
                        },
                    ],
                    createdAt: "2026-05-23T12:00:00Z",
                    updatedAt: "2026-05-23T12:04:30Z",
                },
                {
                    entityId: "vg_enti_f6e5d4c3b2a1",
                    entityType: "VISUAL_STYLE",
                    name: "Pastel watercolor",
                    description: "Soft pastel watercolor look for lifestyle clips.",
                    references: [{ fileId: "vg_file_jzosm31OGi-bPE1eb3qLnA", description: "", isDefault: true }],
                    createdAt: "2026-05-20T09:15:00Z",
                    updatedAt: "2026-05-20T09:15:00Z",
                },
            ],
            hasMore: false,
            nextCursor: null,
        };

        server.mockEndpoint().get("/v1/entities").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.entities.listEntities();
        expect(response).toEqual(rawResponseBody);
    });

    test("createEntity", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            entityType: "VISUAL_STYLE",
            name: "Pastel watercolor",
            description: "Soft pastel watercolor look for lifestyle clips.",
        };
        const rawResponseBody = {
            entityId: "vg_enti_f6e5d4c3b2a1",
            entityType: "VISUAL_STYLE",
            name: "Pastel watercolor",
            description: "Soft pastel watercolor look for lifestyle clips.",
            references: [],
            createdAt: "2026-05-20T09:15:00Z",
            updatedAt: "2026-05-20T09:15:00Z",
        };

        server
            .mockEndpoint()
            .post("/v1/entities")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.entities.createEntity({
            entityType: "VISUAL_STYLE",
            name: "Pastel watercolor",
            description: "Soft pastel watercolor look for lifestyle clips.",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getEntity", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            entityId: "vg_enti_a1b2c3d4e5f6",
            entityType: "ACTOR",
            name: "Maya the host",
            description: "Friendly on-camera host for product explainers.",
            actorConfig: { voiceDisplayName: "Matilda", hasVoice: true, hasAvatarPresenter: true },
            references: [
                {
                    fileId: "vg_file_obLD1OX2eJCrEs0071Z4kA",
                    description: "Front-facing headshot, neutral background.",
                    isDefault: true,
                },
            ],
            createdAt: "2026-05-23T12:00:00Z",
            updatedAt: "2026-05-23T12:04:30Z",
        };

        server
            .mockEndpoint()
            .get("/v1/entities/vg_enti_a1b2c3d4e5f6")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.entities.getEntity({
            entityId: "vg_enti_a1b2c3d4e5f6",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("updateEntity", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "Maya the presenter",
            description: "Friendly on-camera host for product explainers and demos.",
        };
        const rawResponseBody = {
            entityId: "vg_enti_a1b2c3d4e5f6",
            entityType: "ACTOR",
            name: "Maya the presenter",
            description: "Friendly on-camera host for product explainers and demos.",
            actorConfig: { voiceDisplayName: "Matilda", hasVoice: true, hasAvatarPresenter: true },
            references: [
                {
                    fileId: "vg_file_obLD1OX2eJCrEs0071Z4kA",
                    description: "Front-facing headshot, neutral background.",
                    isDefault: true,
                },
            ],
            createdAt: "2026-05-23T12:00:00Z",
            updatedAt: "2026-05-23T13:10:00Z",
        };

        server
            .mockEndpoint()
            .post("/v1/entities/vg_enti_a1b2c3d4e5f6/update")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.entities.updateEntity({
            entityId: "vg_enti_a1b2c3d4e5f6",
            name: "Maya the presenter",
            description: "Friendly on-camera host for product explainers and demos.",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("archiveEntity", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { entityId: "vg_enti_a1b2c3d4e5f6", archived: true };

        server
            .mockEndpoint()
            .post("/v1/entities/vg_enti_a1b2c3d4e5f6/archive")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.entities.archiveEntity({
            entityId: "vg_enti_a1b2c3d4e5f6",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("addEntityReference", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            fileId: "vg_file_mot8bV5POiscDeHyo7TF1g",
            description: "Side profile, studio lighting.",
            isDefault: false,
        };
        const rawResponseBody = {
            entityId: "vg_enti_a1b2c3d4e5f6",
            entityType: "ACTOR",
            name: "Maya the host",
            description: "Friendly on-camera host for product explainers.",
            actorConfig: { voiceDisplayName: "Matilda", hasVoice: true, hasAvatarPresenter: true },
            references: [
                {
                    fileId: "vg_file_obLD1OX2eJCrEs0071Z4kA",
                    description: "Front-facing headshot, neutral background.",
                    isDefault: true,
                },
                {
                    fileId: "vg_file_mot8bV5POiscDeHyo7TF1g",
                    description: "Side profile, studio lighting.",
                    isDefault: false,
                },
            ],
            createdAt: "2026-05-23T12:00:00Z",
            updatedAt: "2026-05-23T14:22:00Z",
        };

        server
            .mockEndpoint()
            .post("/v1/entities/vg_enti_a1b2c3d4e5f6/references")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.entities.addEntityReference({
            entityId: "vg_enti_a1b2c3d4e5f6",
            fileId: "vg_file_mot8bV5POiscDeHyo7TF1g",
            description: "Side profile, studio lighting.",
            isDefault: false,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("removeEntityReference", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { fileId: "vg_file_mot8bV5POiscDeHyo7TF1g" };
        const rawResponseBody = {
            entityId: "vg_enti_a1b2c3d4e5f6",
            entityType: "ACTOR",
            name: "Maya the host",
            description: "Friendly on-camera host for product explainers.",
            actorConfig: { voiceDisplayName: "Matilda", hasVoice: true, hasAvatarPresenter: true },
            references: [
                {
                    fileId: "vg_file_obLD1OX2eJCrEs0071Z4kA",
                    description: "Front-facing headshot, neutral background.",
                    isDefault: true,
                },
            ],
            createdAt: "2026-05-23T12:00:00Z",
            updatedAt: "2026-05-23T14:25:00Z",
        };

        server
            .mockEndpoint()
            .post("/v1/entities/vg_enti_a1b2c3d4e5f6/references/remove")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.entities.removeEntityReference({
            entityId: "vg_enti_a1b2c3d4e5f6",
            fileId: "vg_file_mot8bV5POiscDeHyo7TF1g",
        });
        expect(response).toEqual(rawResponseBody);
    });
});
