// This file was auto-generated by Fern from our API Definition.

import { VideoGenClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("FilesClient", () => {
    test("getFiles", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            files: [
                {
                    fileId: "fileId",
                    type: "IMAGE",
                    scope: "GLOBAL",
                    displayName: "displayName",
                    description: "description",
                    durationSeconds: 1.1,
                    transcript: "transcript",
                    thumbnailSource: { status: "pending" },
                    previewSource: { status: "pending" },
                    downloadSource: { status: "pending" },
                    hlsSource: { status: "pending" },
                    isPublicPreviewEnabled: true,
                    publicHlsUrl: "publicHlsUrl",
                    publicPlaybackId: "publicPlaybackId",
                    sourceToolType: "sourceToolType",
                    sourceToolExecutionId: "sourceToolExecutionId",
                },
            ],
        };

        server.mockEndpoint().get("/v1/files").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.files.getFiles();
        expect(response).toEqual(rawResponseBody);
    });

    test("searchFiles", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { query: "query" };
        const rawResponseBody = { results: [{ similarity: 0.82, file: { fileId: "fileId", scope: "GLOBAL" } }] };

        server
            .mockEndpoint()
            .post("/v1/files/search")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.files.searchFiles({
            query: "query",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getFile", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            fileId: "fileId",
            type: "IMAGE",
            scope: "GLOBAL",
            displayName: "displayName",
            description: "description",
            durationSeconds: 1.1,
            transcript: "transcript",
            thumbnailSource: { status: "pending", url: "url", expiresAt: 1.1, width: 1, height: 1, fileBytes: 1 },
            previewSource: { status: "pending", url: "url", expiresAt: 1.1, width: 1, height: 1, fileBytes: 1 },
            downloadSource: { status: "pending", url: "url", expiresAt: 1.1, width: 1, height: 1, fileBytes: 1 },
            hlsSource: { status: "pending", url: "url", expiresAt: 1.1, width: 1, height: 1, fileBytes: 1 },
            isPublicPreviewEnabled: true,
            publicHlsUrl: "publicHlsUrl",
            publicPlaybackId: "publicPlaybackId",
            sourceToolType: "sourceToolType",
            sourceToolExecutionId: "sourceToolExecutionId",
        };

        server.mockEndpoint().get("/v1/files/fileId").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.files.getFile({
            fileId: "fileId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createFileUpload", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { displayName: "displayName" };
        const rawResponseBody = { fileId: "fileId", uploadUrl: "uploadUrl" };

        server
            .mockEndpoint()
            .post("/v1/files/upload")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.files.createFileUpload({
            displayName: "displayName",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("hydrateFile", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            fileId: "fileId",
            type: "IMAGE",
            scope: "GLOBAL",
            displayName: "displayName",
            description: "description",
            durationSeconds: 1.1,
            transcript: "transcript",
            thumbnailSource: { status: "pending", url: "url", expiresAt: 1.1, width: 1, height: 1, fileBytes: 1 },
            previewSource: { status: "pending", url: "url", expiresAt: 1.1, width: 1, height: 1, fileBytes: 1 },
            downloadSource: { status: "pending", url: "url", expiresAt: 1.1, width: 1, height: 1, fileBytes: 1 },
            hlsSource: { status: "pending", url: "url", expiresAt: 1.1, width: 1, height: 1, fileBytes: 1 },
            isPublicPreviewEnabled: true,
            publicHlsUrl: "publicHlsUrl",
            publicPlaybackId: "publicPlaybackId",
            sourceToolType: "sourceToolType",
            sourceToolExecutionId: "sourceToolExecutionId",
        };

        server
            .mockEndpoint()
            .post("/v1/files/fileId/hydrate")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.files.hydrateFile({
            fileId: "fileId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("archiveFile", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            fileId: "fileId",
            type: "IMAGE",
            scope: "GLOBAL",
            displayName: "displayName",
            description: "description",
            durationSeconds: 1.1,
            transcript: "transcript",
            thumbnailSource: { status: "pending", url: "url", expiresAt: 1.1, width: 1, height: 1, fileBytes: 1 },
            previewSource: { status: "pending", url: "url", expiresAt: 1.1, width: 1, height: 1, fileBytes: 1 },
            downloadSource: { status: "pending", url: "url", expiresAt: 1.1, width: 1, height: 1, fileBytes: 1 },
            hlsSource: { status: "pending", url: "url", expiresAt: 1.1, width: 1, height: 1, fileBytes: 1 },
            isPublicPreviewEnabled: true,
            publicHlsUrl: "publicHlsUrl",
            publicPlaybackId: "publicPlaybackId",
            sourceToolType: "sourceToolType",
            sourceToolExecutionId: "sourceToolExecutionId",
        };

        server
            .mockEndpoint()
            .post("/v1/files/fileId/archive")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.files.archiveFile({
            fileId: "fileId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("enablePublicPreview", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            fileId: "fileId",
            type: "IMAGE",
            scope: "GLOBAL",
            displayName: "displayName",
            description: "description",
            durationSeconds: 1.1,
            transcript: "transcript",
            thumbnailSource: { status: "pending", url: "url", expiresAt: 1.1, width: 1, height: 1, fileBytes: 1 },
            previewSource: { status: "pending", url: "url", expiresAt: 1.1, width: 1, height: 1, fileBytes: 1 },
            downloadSource: { status: "pending", url: "url", expiresAt: 1.1, width: 1, height: 1, fileBytes: 1 },
            hlsSource: { status: "pending", url: "url", expiresAt: 1.1, width: 1, height: 1, fileBytes: 1 },
            isPublicPreviewEnabled: true,
            publicHlsUrl: "publicHlsUrl",
            publicPlaybackId: "publicPlaybackId",
            sourceToolType: "sourceToolType",
            sourceToolExecutionId: "sourceToolExecutionId",
        };

        server
            .mockEndpoint()
            .post("/v1/files/fileId/enable-public-preview")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.files.enablePublicPreview({
            fileId: "fileId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("disablePublicPreview", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            fileId: "fileId",
            type: "IMAGE",
            scope: "GLOBAL",
            displayName: "displayName",
            description: "description",
            durationSeconds: 1.1,
            transcript: "transcript",
            thumbnailSource: { status: "pending", url: "url", expiresAt: 1.1, width: 1, height: 1, fileBytes: 1 },
            previewSource: { status: "pending", url: "url", expiresAt: 1.1, width: 1, height: 1, fileBytes: 1 },
            downloadSource: { status: "pending", url: "url", expiresAt: 1.1, width: 1, height: 1, fileBytes: 1 },
            hlsSource: { status: "pending", url: "url", expiresAt: 1.1, width: 1, height: 1, fileBytes: 1 },
            isPublicPreviewEnabled: true,
            publicHlsUrl: "publicHlsUrl",
            publicPlaybackId: "publicPlaybackId",
            sourceToolType: "sourceToolType",
            sourceToolExecutionId: "sourceToolExecutionId",
        };

        server
            .mockEndpoint()
            .post("/v1/files/fileId/disable-public-preview")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.files.disablePublicPreview({
            fileId: "fileId",
        });
        expect(response).toEqual(rawResponseBody);
    });
});
