// This file was auto-generated by Fern from our API Definition.

import { VideogenApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("PetsClient", () => {
    test("listPets", async () => {
        const server = mockServerPool.createServer();
        const client = new VideogenApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = [{ id: "id", name: "name", tag: "tag" }];
        server.mockEndpoint().get("/pets").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.pets.listPets();
        expect(response).toEqual([
            {
                id: "id",
                name: "name",
                tag: "tag",
            },
        ]);
    });

    test("createPet", async () => {
        const server = mockServerPool.createServer();
        const client = new VideogenApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { id: "id", name: "name", tag: "tag" };
        server
            .mockEndpoint()
            .post("/pets")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.pets.createPet({
            name: "name",
        });
        expect(response).toEqual({
            id: "id",
            name: "name",
            tag: "tag",
        });
    });

    test("getPet", async () => {
        const server = mockServerPool.createServer();
        const client = new VideogenApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { id: "id", name: "name", tag: "tag" };
        server.mockEndpoint().get("/pets/petId").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.pets.getPet({
            petId: "petId",
        });
        expect(response).toEqual({
            id: "id",
            name: "name",
            tag: "tag",
        });
    });
});
