// This file was auto-generated by Fern from our API Definition.

import { VideoGenClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ProjectsClient", () => {
    test("listProjects", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            projects: [
                {
                    projectId: "projectId",
                    title: "title",
                    aspectRatio: { width: 1, height: 1 },
                    status: "generating",
                    createdAt: "2024-01-15T09:30:00Z",
                    updatedAt: "2024-01-15T09:30:00Z",
                    projectUrl: "projectUrl",
                },
            ],
            hasMore: true,
            nextCursor: "nextCursor",
        };

        server.mockEndpoint().get("/v1/projects").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.projects.listProjects();
        expect(response).toEqual(rawResponseBody);
    });

    test("getProject", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            projectId: "projectId",
            title: "title",
            aspectRatio: { width: 1, height: 1 },
            status: "generating",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            projectUrl: "projectUrl",
        };

        server
            .mockEndpoint()
            .get("/v1/projects/projectId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.projects.getProject({
            projectId: "projectId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("exportProject", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { exportId: "exportId" };

        server
            .mockEndpoint()
            .post("/v1/projects/projectId/export")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.projects.exportProject({
            projectId: "projectId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getProjectExport", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            exportId: "exportId",
            projectId: "projectId",
            status: "pending",
            progressPercentage: 1.1,
            attemptIndex: 1,
            downloadUrl: "downloadUrl",
            thumbnailUrl: "thumbnailUrl",
            error: {
                message: "message",
                code: "code",
                requirement: { type: "type", details: { key: "value" } },
                internalErrorCode: "internalErrorCode",
            },
        };

        server
            .mockEndpoint()
            .get("/v1/projects/projectId/exports/exportId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.projects.getProjectExport({
            projectId: "projectId",
            exportId: "exportId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("remixProject", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { remixActions: [{ type: "SET_BACKGROUND_MUSIC" }] };
        const rawResponseBody = {
            projectId: "projectId",
            projectUrl: "projectUrl",
            remixActionIds: ["remixActionIds"],
        };

        server
            .mockEndpoint()
            .post("/v1/projects/projectId/remix")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.projects.remixProject({
            projectId: "projectId",
            remixActions: [
                {
                    type: "SET_BACKGROUND_MUSIC",
                },
            ],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listProjectRemixActions", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            remixActions: [
                {
                    remixActionId: "remixActionId",
                    type: "SET_BACKGROUND_MUSIC",
                    status: "pending",
                    projectId: "projectId",
                    projectUrl: "projectUrl",
                    progressPercentage: 1.1,
                    attemptIndex: 1,
                    error: { message: "message" },
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/v1/projects/projectId/remix-actions")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.projects.listProjectRemixActions({
            projectId: "projectId",
        });
        expect(response).toEqual(rawResponseBody);
    });
});
