// This file was auto-generated by Fern from our API Definition.

import { VideoGenClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ProjectsClient", () => {
    test("listProjects", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            projects: [
                {
                    projectId: "1f0a2b3c-4d5e-6789-ab12-cdef34567890",
                    title: "Staying hydrated",
                    aspectRatio: { width: 16, height: 9 },
                    status: "ready",
                    createdAt: "2026-05-23T12:00:00Z",
                    updatedAt: "2026-05-23T12:04:30Z",
                    projectUrl: "https://app.videogen.io/project/1f0a2b3c-4d5e-6789-ab12-cdef34567890",
                },
            ],
            hasMore: false,
            nextCursor: null,
        };

        server.mockEndpoint().get("/v1/projects").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.projects.listProjects();
        expect(response).toEqual(rawResponseBody);
    });

    test("getProject", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            projectId: "1f0a2b3c-4d5e-6789-ab12-cdef34567890",
            title: "Staying hydrated",
            aspectRatio: { width: 16, height: 9 },
            status: "ready",
            createdAt: "2026-05-23T12:00:00Z",
            updatedAt: "2026-05-23T12:04:30Z",
            projectUrl: "https://app.videogen.io/project/1f0a2b3c-4d5e-6789-ab12-cdef34567890",
        };

        server
            .mockEndpoint()
            .get("/v1/projects/1f0a2b3c-4d5e-6789-ab12-cdef34567890")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.projects.getProject({
            projectId: "1f0a2b3c-4d5e-6789-ab12-cdef34567890",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("exportProject", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { quality: "FULL_HIGH" };
        const rawResponseBody = { exportId: "2a1b3c4d-5e6f-7890-ab12-cdef34567890" };

        server
            .mockEndpoint()
            .post("/v1/projects/1f0a2b3c-4d5e-6789-ab12-cdef34567890/export")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.projects.exportProject({
            projectId: "1f0a2b3c-4d5e-6789-ab12-cdef34567890",
            quality: "FULL_HIGH",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getProjectExport", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            exportId: "2a1b3c4d-5e6f-7890-ab12-cdef34567890",
            projectId: "1f0a2b3c-4d5e-6789-ab12-cdef34567890",
            status: "succeeded",
            progressPercentage: 100,
            attemptIndex: 0,
            downloadUrl: "https://stream.media.videogen.io/example/1080p.mp4?token=abc&download=Staying%20hydrated.mp4",
            thumbnailUrl: "https://image.media.videogen.io/example/thumbnail.jpg?token=abc",
        };

        server
            .mockEndpoint()
            .get("/v1/projects/1f0a2b3c-4d5e-6789-ab12-cdef34567890/exports/2a1b3c4d-5e6f-7890-ab12-cdef34567890")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.projects.getProjectExport({
            projectId: "1f0a2b3c-4d5e-6789-ab12-cdef34567890",
            exportId: "2a1b3c4d-5e6f-7890-ab12-cdef34567890",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("remixProject", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { remixActions: [{ type: "SET_BACKGROUND_MUSIC" }] };
        const rawResponseBody = {
            projectId: "projectId",
            projectUrl: "projectUrl",
            remixActionIds: ["remixActionIds"],
        };

        server
            .mockEndpoint()
            .post("/v1/projects/projectId/remix")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.projects.remixProject({
            projectId: "projectId",
            remixActions: [
                {
                    type: "SET_BACKGROUND_MUSIC",
                },
            ],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listProjectRemixActions", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            remixActions: [
                {
                    remixActionId: "remixActionId",
                    type: "SET_BACKGROUND_MUSIC",
                    status: "pending",
                    projectId: "projectId",
                    projectUrl: "projectUrl",
                    progressPercentage: 1.1,
                    attemptIndex: 1,
                    error: { message: "message" },
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/v1/projects/projectId/remix-actions")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.projects.listProjectRemixActions({
            projectId: "projectId",
        });
        expect(response).toEqual(rawResponseBody);
    });
});
