// This file was auto-generated by Fern from our API Definition.

import { VideogenApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ResourcesClient", () => {
    test("listAvatarPresenters", async () => {
        const server = mockServerPool.createServer();
        const client = new VideogenApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            avatarPresenters: [
                {
                    avatarPresenterId: "avatarPresenterId",
                    displayableGender: "MALE",
                    imageUrl: "imageUrl",
                    thumbnailUrl: "thumbnailUrl",
                    previewVideoUrl: "previewVideoUrl",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/v1/resources/avatar-presenters")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.resources.listAvatarPresenters();
        expect(response).toEqual(rawResponseBody);
    });

    test("listTtsVoices", async () => {
        const server = mockServerPool.createServer();
        const client = new VideogenApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            ttsVoices: [
                {
                    voiceId: "voiceId",
                    providerName: "providerName",
                    languageCode: "languageCode",
                    displayName: "displayName",
                    displayGender: "MALE",
                    accent: "accent",
                    description: "description",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/v1/resources/tts-voices")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.resources.listTtsVoices();
        expect(response).toEqual(rawResponseBody);
    });
});
