// This file was auto-generated by Fern from our API Definition.

import { VideoGenClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ResourcesClient", () => {
    test("listAvatarPresenters", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            avatarPresenters: [
                {
                    avatarPresenterId: "vg_pres_a1ua8slxzfi",
                    displayableGender: "FEMALE",
                    imageUrl: "https://clips-presenters.d-id.com/mary/26F6sVe7Yg/ujy8kGzgSJ/image.png",
                    thumbnailUrl: "https://clips-presenters.d-id.com/mary/26F6sVe7Yg/ujy8kGzgSJ/thumbnail.png",
                    previewVideoUrl: "https://clips-presenters.d-id.com/mary/26F6sVe7Yg/ujy8kGzgSJ/preview.mp4",
                },
            ],
            hasMore: false,
            nextCursor: null,
        };

        server
            .mockEndpoint()
            .get("/v1/resources/avatar-presenters")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.resources.listAvatarPresenters();
        expect(response).toEqual(rawResponseBody);
    });

    test("listTtsVoices", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            ttsVoices: [
                {
                    voiceId: "vg_voic_7t1wdka3tmk",
                    languageCode: "en-US",
                    displayName: "Matilda",
                    displayGender: "FEMALE",
                    accent: "american",
                    description: "A professional woman with a pleasing alto pitch.",
                    supportsDirectToolExecution: false,
                    supportsAllLanguages: true,
                    isDeprecated: false,
                },
            ],
            hasMore: false,
            nextCursor: null,
        };

        server
            .mockEndpoint()
            .get("/v1/resources/tts-voices")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.resources.listTtsVoices();
        expect(response).toEqual(rawResponseBody);
    });

    test("listLanguages", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { languages: [{ languageCode: "languageCode", name: "name" }] };

        server
            .mockEndpoint()
            .get("/v1/resources/languages")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.resources.listLanguages();
        expect(response).toEqual(rawResponseBody);
    });
});
