// This file was auto-generated by Fern from our API Definition.

import { VideoGenClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("TextClient", () => {
    test("generateText", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { prompt: "Write a 30-second upbeat video script about why the sky is blue." };
        const rawResponseBody = { text: "text" };

        server
            .mockEndpoint()
            .post("/v1/text/generate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.text.generateText({
            prompt: "Write a 30-second upbeat video script about why the sky is blue.",
        });
        expect(response).toEqual(rawResponseBody);
    });
});
