// This file was auto-generated by Fern from our API Definition.

import { VideogenApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ToolsClient", () => {
    test("generateImage", async () => {
        const server = mockServerPool.createServer();
        const client = new VideogenApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { prompt: "prompt" };
        const rawResponseBody = { executionId: "executionId" };
        server
            .mockEndpoint()
            .post("/v1/tools/generate-image")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.generateImage({
            prompt: "prompt",
        });
        expect(response).toEqual({
            executionId: "executionId",
        });
    });

    test("generateVideoClip", async () => {
        const server = mockServerPool.createServer();
        const client = new VideogenApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { prompt: "prompt", generateAudio: true };
        const rawResponseBody = { executionId: "executionId" };
        server
            .mockEndpoint()
            .post("/v1/tools/generate-video-clip")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.generateVideoClip({
            prompt: "prompt",
            generateAudio: true,
        });
        expect(response).toEqual({
            executionId: "executionId",
        });
    });

    test("generateVideoFromImage", async () => {
        const server = mockServerPool.createServer();
        const client = new VideogenApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { prompt: "prompt", generateAudio: true, image: { fileId: "fileId" } };
        const rawResponseBody = { executionId: "executionId" };
        server
            .mockEndpoint()
            .post("/v1/tools/generate-video-from-image")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.generateVideoFromImage({
            prompt: "prompt",
            generateAudio: true,
            image: {
                fileId: "fileId",
            },
        });
        expect(response).toEqual({
            executionId: "executionId",
        });
    });

    test("generateTts", async () => {
        const server = mockServerPool.createServer();
        const client = new VideogenApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { ttsText: "ttsText" };
        const rawResponseBody = { executionId: "executionId" };
        server
            .mockEndpoint()
            .post("/v1/tools/generate-tts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.generateTts({
            ttsText: "ttsText",
        });
        expect(response).toEqual({
            executionId: "executionId",
        });
    });

    test("generateSoundEffect", async () => {
        const server = mockServerPool.createServer();
        const client = new VideogenApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { prompt: "prompt" };
        const rawResponseBody = { executionId: "executionId" };
        server
            .mockEndpoint()
            .post("/v1/tools/generate-sound-effect")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.generateSoundEffect({
            prompt: "prompt",
        });
        expect(response).toEqual({
            executionId: "executionId",
        });
    });

    test("generateAvatar", async () => {
        const server = mockServerPool.createServer();
        const client = new VideogenApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { presenterDescription: "presenterDescription" };
        const rawResponseBody = { executionId: "executionId" };
        server
            .mockEndpoint()
            .post("/v1/tools/generate-avatar")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.generateAvatar({
            presenterDescription: "presenterDescription",
        });
        expect(response).toEqual({
            executionId: "executionId",
        });
    });

    test("vectorizeImage", async () => {
        const server = mockServerPool.createServer();
        const client = new VideogenApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { image: { fileId: "fileId" } };
        const rawResponseBody = { executionId: "executionId" };
        server
            .mockEndpoint()
            .post("/v1/tools/vectorize-image")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.vectorizeImage({
            image: {
                fileId: "fileId",
            },
        });
        expect(response).toEqual({
            executionId: "executionId",
        });
    });

    test("removeImageBackground", async () => {
        const server = mockServerPool.createServer();
        const client = new VideogenApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { image: { fileId: "fileId" } };
        const rawResponseBody = { executionId: "executionId" };
        server
            .mockEndpoint()
            .post("/v1/tools/remove-image-background")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.removeImageBackground({
            image: {
                fileId: "fileId",
            },
        });
        expect(response).toEqual({
            executionId: "executionId",
        });
    });

    test("removeVideoBackground", async () => {
        const server = mockServerPool.createServer();
        const client = new VideogenApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { video: { fileId: "fileId" } };
        const rawResponseBody = { executionId: "executionId" };
        server
            .mockEndpoint()
            .post("/v1/tools/remove-video-background")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.removeVideoBackground({
            video: {
                fileId: "fileId",
            },
        });
        expect(response).toEqual({
            executionId: "executionId",
        });
    });

    test("getExecutedTool", async () => {
        const server = mockServerPool.createServer();
        const client = new VideogenApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            executionId: "executionId",
            status: "pending",
            toolType: "toolType",
            result: { key: "value" },
            error: { message: "message", code: "code" },
        };
        server
            .mockEndpoint()
            .get("/v1/tools/executions/executionId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.getExecutedTool({
            executionId: "executionId",
        });
        expect(response).toEqual({
            executionId: "executionId",
            status: "pending",
            toolType: "toolType",
            result: {
                key: "value",
            },
            error: {
                message: "message",
                code: "code",
            },
        });
    });
});
