// This file was auto-generated by Fern from our API Definition.

import { VideoGenClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ToolsClient", () => {
    test("generateImage", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { prompt: "A serene Japanese garden with cherry blossoms at golden hour" };
        const rawResponseBody = { toolExecutionId: "toolExecutionId" };

        server
            .mockEndpoint()
            .post("/v1/tools/generate-image")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.generateImage({
            prompt: "A serene Japanese garden with cherry blossoms at golden hour",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("generateVideoClip", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { toolExecutionId: "toolExecutionId" };

        server
            .mockEndpoint()
            .post("/v1/tools/generate-video-clip")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.generateVideoClip();
        expect(response).toEqual(rawResponseBody);
    });

    test("textToSpeech", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { ttsText: "ttsText" };
        const rawResponseBody = { toolExecutionId: "toolExecutionId" };

        server
            .mockEndpoint()
            .post("/v1/tools/text-to-speech")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.textToSpeech({
            ttsText: "ttsText",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("generateSoundEffect", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { prompt: "prompt" };
        const rawResponseBody = { toolExecutionId: "toolExecutionId" };

        server
            .mockEndpoint()
            .post("/v1/tools/generate-sound-effect")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.generateSoundEffect({
            prompt: "prompt",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("generateAvatar", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { avatarPresenterId: "avatarPresenterId", audioStorageFileId: "audioStorageFileId" };
        const rawResponseBody = { toolExecutionId: "toolExecutionId" };

        server
            .mockEndpoint()
            .post("/v1/tools/generate-avatar")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.generateAvatar({
            avatarPresenterId: "avatarPresenterId",
            audioStorageFileId: "audioStorageFileId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("vectorizeImage", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { imageStorageFileId: "imageStorageFileId" };
        const rawResponseBody = { toolExecutionId: "toolExecutionId" };

        server
            .mockEndpoint()
            .post("/v1/tools/vectorize-image")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.vectorizeImage({
            imageStorageFileId: "imageStorageFileId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("removeImageBackground", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { imageStorageFileId: "imageStorageFileId" };
        const rawResponseBody = { toolExecutionId: "toolExecutionId" };

        server
            .mockEndpoint()
            .post("/v1/tools/remove-image-background")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.removeImageBackground({
            imageStorageFileId: "imageStorageFileId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("removeVideoBackground", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { videoStorageFileId: "videoStorageFileId" };
        const rawResponseBody = { toolExecutionId: "toolExecutionId" };

        server
            .mockEndpoint()
            .post("/v1/tools/remove-video-background")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.removeVideoBackground({
            videoStorageFileId: "videoStorageFileId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("upscaleImage", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { imageStorageFileId: "imageStorageFileId" };
        const rawResponseBody = { toolExecutionId: "toolExecutionId" };

        server
            .mockEndpoint()
            .post("/v1/tools/upscale-image")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.upscaleImage({
            imageStorageFileId: "imageStorageFileId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("upscaleVideo", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { videoStorageFileId: "videoStorageFileId" };
        const rawResponseBody = { toolExecutionId: "toolExecutionId" };

        server
            .mockEndpoint()
            .post("/v1/tools/upscale-video")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.upscaleVideo({
            videoStorageFileId: "videoStorageFileId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("cancelToolExecution", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { toolExecutionId: "toolExecutionId" };

        server
            .mockEndpoint()
            .post("/v1/tools/executions/toolExecutionId/cancel")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.cancelToolExecution({
            toolExecutionId: "toolExecutionId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getToolExecutionInfo", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            toolExecutionId: "toolExecutionId",
            status: "pending",
            toolType: "toolType",
            results: [{ fileId: "fileId", type: "IMAGE", file: { fileId: "fileId", scope: "GLOBAL" } }],
            error: {
                message: "message",
                code: "code",
                requirement: { type: "type", details: { key: "value" } },
                internalErrorCode: "internalErrorCode",
            },
        };

        server
            .mockEndpoint()
            .get("/v1/tools/executions/toolExecutionId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.getToolExecutionInfo({
            toolExecutionId: "toolExecutionId",
        });
        expect(response).toEqual(rawResponseBody);
    });
});
