// This file was auto-generated by Fern from our API Definition.

import { VideoGenClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ToolsClient", () => {
    test("promptToImage", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { prompt: "prompt" };
        const rawResponseBody = { toolExecutionId: "toolExecutionId" };

        server
            .mockEndpoint()
            .post("/v1/tools/prompt-to-image")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.promptToImage({
            prompt: "prompt",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("promptToVideoClip", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { prompt: "prompt" };
        const rawResponseBody = { toolExecutionId: "toolExecutionId" };

        server
            .mockEndpoint()
            .post("/v1/tools/prompt-to-video-clip")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.promptToVideoClip({
            prompt: "prompt",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("imageToVideoClip", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { imageStorageFileId: "imageStorageFileId" };
        const rawResponseBody = { toolExecutionId: "toolExecutionId" };

        server
            .mockEndpoint()
            .post("/v1/tools/image-to-video-clip")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.imageToVideoClip({
            imageStorageFileId: "imageStorageFileId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("imageToImage", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { imageStorageFileId: "imageStorageFileId", prompt: "prompt" };
        const rawResponseBody = { toolExecutionId: "toolExecutionId" };

        server
            .mockEndpoint()
            .post("/v1/tools/image-to-image")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.imageToImage({
            imageStorageFileId: "imageStorageFileId",
            prompt: "prompt",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("videoToVideoClip", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { videoStorageFileId: "videoStorageFileId", prompt: "prompt" };
        const rawResponseBody = { toolExecutionId: "toolExecutionId" };

        server
            .mockEndpoint()
            .post("/v1/tools/video-to-video-clip")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.videoToVideoClip({
            videoStorageFileId: "videoStorageFileId",
            prompt: "prompt",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("textToSpeech", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { ttsText: "ttsText" };
        const rawResponseBody = { toolExecutionId: "toolExecutionId" };

        server
            .mockEndpoint()
            .post("/v1/tools/text-to-speech")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.textToSpeech({
            ttsText: "ttsText",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("promptToSoundEffect", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { prompt: "prompt" };
        const rawResponseBody = { toolExecutionId: "toolExecutionId" };

        server
            .mockEndpoint()
            .post("/v1/tools/prompt-to-sound-effect")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.promptToSoundEffect({
            prompt: "prompt",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("audioToAvatarClip", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { avatarPresenterId: "avatarPresenterId", audioStorageFileId: "audioStorageFileId" };
        const rawResponseBody = { toolExecutionId: "toolExecutionId" };

        server
            .mockEndpoint()
            .post("/v1/tools/audio-to-avatar-clip")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.audioToAvatarClip({
            avatarPresenterId: "avatarPresenterId",
            audioStorageFileId: "audioStorageFileId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("vectorizeImage", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { imageStorageFileId: "imageStorageFileId" };
        const rawResponseBody = { toolExecutionId: "toolExecutionId" };

        server
            .mockEndpoint()
            .post("/v1/tools/vectorize-image")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.vectorizeImage({
            imageStorageFileId: "imageStorageFileId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("removeImageBackground", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { imageStorageFileId: "imageStorageFileId" };
        const rawResponseBody = { toolExecutionId: "toolExecutionId" };

        server
            .mockEndpoint()
            .post("/v1/tools/remove-image-background")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.removeImageBackground({
            imageStorageFileId: "imageStorageFileId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("removeVideoBackground", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { videoStorageFileId: "videoStorageFileId" };
        const rawResponseBody = { toolExecutionId: "toolExecutionId" };

        server
            .mockEndpoint()
            .post("/v1/tools/remove-video-background")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.removeVideoBackground({
            videoStorageFileId: "videoStorageFileId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("upscaleImage", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { imageStorageFileId: "imageStorageFileId" };
        const rawResponseBody = { toolExecutionId: "toolExecutionId" };

        server
            .mockEndpoint()
            .post("/v1/tools/upscale-image")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.upscaleImage({
            imageStorageFileId: "imageStorageFileId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("upscaleVideo", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { videoStorageFileId: "videoStorageFileId" };
        const rawResponseBody = { toolExecutionId: "toolExecutionId" };

        server
            .mockEndpoint()
            .post("/v1/tools/upscale-video")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.upscaleVideo({
            videoStorageFileId: "videoStorageFileId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("cancelToolExecution", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { toolExecutionId: "toolExecutionId" };

        server
            .mockEndpoint()
            .post("/v1/tools/executions/toolExecutionId/cancel")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.cancelToolExecution({
            toolExecutionId: "toolExecutionId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getToolExecutionInfo", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            toolExecutionId: "toolExecutionId",
            status: "pending",
            toolType: "toolType",
            results: [
                {
                    storageFileId: "storageFileId",
                    type: "IMAGE",
                    file: { storageFileId: "storageFileId", type: "IMAGE", scope: "GLOBAL" },
                },
            ],
            error: { message: "message", code: "code" },
        };

        server
            .mockEndpoint()
            .get("/v1/tools/executions/toolExecutionId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.getToolExecutionInfo({
            toolExecutionId: "toolExecutionId",
        });
        expect(response).toEqual(rawResponseBody);
    });
});
