// This file was auto-generated by Fern from our API Definition.

import { VideoGenClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("WebhooksClient", () => {
    test("listWebhookEndpoints", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            endpoints: [
                {
                    endpointId: "endpointId",
                    url: "url",
                    events: ["tool_execution.succeeded"],
                    description: "description",
                    createdAt: 1.1,
                    signingSecret: "signingSecret",
                    signingSecretLast4: "signingSecretLast4",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/v1/webhooks/endpoints")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.webhooks.listWebhookEndpoints();
        expect(response).toEqual(rawResponseBody);
    });

    test("createWebhookEndpoint", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { url: "url", events: ["tool_execution.succeeded"] };
        const rawResponseBody = {
            endpointId: "endpointId",
            url: "url",
            events: ["tool_execution.succeeded"],
            description: "description",
            createdAt: 1.1,
            signingSecret: "signingSecret",
            signingSecretLast4: "signingSecretLast4",
        };

        server
            .mockEndpoint()
            .post("/v1/webhooks/endpoints")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.webhooks.createWebhookEndpoint({
            url: "url",
            events: ["tool_execution.succeeded"],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("deleteWebhookEndpoint", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/v1/webhooks/endpoints/endpointId").respondWith().statusCode(200).build();

        const response = await client.webhooks.deleteWebhookEndpoint({
            endpointId: "endpointId",
        });
        expect(response).toEqual(undefined);
    });
});
