// This file was auto-generated by Fern from our API Definition.

import { VideoGenClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("WorkflowsClient", () => {
    test("scriptToVideo", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { script: "script", visualStyle: { type: "STOCK" } };
        const rawResponseBody = {
            workflowRunId: "workflowRunId",
            projectId: "projectId",
            projectUrl: "projectUrl",
            remixActionIds: ["remixActionIds"],
        };

        server
            .mockEndpoint()
            .post("/v1/workflows/script-to-video")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.workflows.scriptToVideo({
            script: "script",
            visualStyle: {
                type: "STOCK",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("addVisualsNarrationsAndCaptionsToScript", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { script: "script", visualStyle: { type: "STOCK" } };
        const rawResponseBody = {
            workflowRunId: "workflowRunId",
            projectId: "projectId",
            projectUrl: "projectUrl",
            remixActionIds: ["remixActionIds"],
        };

        server
            .mockEndpoint()
            .post("/v1/workflows/add-visuals-narrations-and-captions-to-script")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.workflows.addVisualsNarrationsAndCaptionsToScript({
            script: "script",
            visualStyle: {
                type: "STOCK",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("voiceoverToVideo", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { fileId: "fileId", visualStyle: { type: "STOCK" } };
        const rawResponseBody = {
            workflowRunId: "workflowRunId",
            projectId: "projectId",
            projectUrl: "projectUrl",
            remixActionIds: ["remixActionIds"],
        };

        server
            .mockEndpoint()
            .post("/v1/workflows/voiceover-to-video")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.workflows.voiceoverToVideo({
            fileId: "fileId",
            visualStyle: {
                type: "STOCK",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("addVisualsAndCaptionsToVoiceover", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { fileId: "fileId", visualStyle: { type: "STOCK" } };
        const rawResponseBody = {
            workflowRunId: "workflowRunId",
            projectId: "projectId",
            projectUrl: "projectUrl",
            remixActionIds: ["remixActionIds"],
        };

        server
            .mockEndpoint()
            .post("/v1/workflows/add-visuals-and-captions-to-voiceover")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.workflows.addVisualsAndCaptionsToVoiceover({
            fileId: "fileId",
            visualStyle: {
                type: "STOCK",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("slideshowToVideo", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { fileId: "fileId" };
        const rawResponseBody = {
            workflowRunId: "workflowRunId",
            projectId: "projectId",
            projectUrl: "projectUrl",
            remixActionIds: ["remixActionIds"],
        };

        server
            .mockEndpoint()
            .post("/v1/workflows/slideshow-to-video")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.workflows.slideshowToVideo({
            fileId: "fileId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("addNarrationTransitionsAndCaptionsToSlideshow", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { fileId: "fileId" };
        const rawResponseBody = {
            workflowRunId: "workflowRunId",
            projectId: "projectId",
            projectUrl: "projectUrl",
            remixActionIds: ["remixActionIds"],
        };

        server
            .mockEndpoint()
            .post("/v1/workflows/add-narration-transitions-and-captions-to-slideshow")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.workflows.addNarrationTransitionsAndCaptionsToSlideshow({
            fileId: "fileId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("storyboardToVideo", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { scenes: [{ prompt: "prompt" }] };
        const rawResponseBody = {
            workflowRunId: "workflowRunId",
            projectId: "projectId",
            projectUrl: "projectUrl",
            remixActionIds: ["remixActionIds"],
        };

        server
            .mockEndpoint()
            .post("/v1/workflows/storyboard-to-video")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.workflows.storyboardToVideo({
            scenes: [
                {
                    prompt: "prompt",
                },
            ],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("generateScenesFromStoryboard", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { scenes: [{ prompt: "prompt" }] };
        const rawResponseBody = {
            workflowRunId: "workflowRunId",
            projectId: "projectId",
            projectUrl: "projectUrl",
            remixActionIds: ["remixActionIds"],
        };

        server
            .mockEndpoint()
            .post("/v1/workflows/generate-scenes-from-storyboard")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.workflows.generateScenesFromStoryboard({
            scenes: [
                {
                    prompt: "prompt",
                },
            ],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getWorkflowRun", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            workflowRunId: "workflowRunId",
            status: "pending",
            workflowType: "SCRIPT_TO_VIDEO",
            progressPercentage: 1.1,
            attemptIndex: 1,
            projectId: "projectId",
            projectUrl: "projectUrl",
            error: {
                message: "message",
                code: "code",
                requirement: { type: "type", details: { key: "value" } },
                internalErrorCode: "internalErrorCode",
            },
        };

        server
            .mockEndpoint()
            .get("/v1/workflows/runs/workflowRunId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.workflows.getWorkflowRun({
            workflowRunId: "workflowRunId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("cancelWorkflowRun", async () => {
        const server = mockServerPool.createServer();
        const client = new VideoGenClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            workflowRunId: "workflowRunId",
            projectId: "projectId",
            projectUrl: "projectUrl",
            remixActionIds: ["remixActionIds"],
        };

        server
            .mockEndpoint()
            .post("/v1/workflows/runs/workflowRunId/cancel")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.workflows.cancelWorkflowRun({
            workflowRunId: "workflowRunId",
        });
        expect(response).toEqual(rawResponseBody);
    });
});
