// This file was auto-generated by Fern from our API Definition.

import { FilesClient } from "./api/resources/files/client/Client.js";
import { ToolsClient } from "./api/resources/tools/client/Client.js";
import { WebhooksClient } from "./api/resources/webhooks/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";

export declare namespace VideogenApiClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class VideogenApiClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<VideogenApiClient.Options>;
    protected _files: FilesClient | undefined;
    protected _webhooks: WebhooksClient | undefined;
    protected _tools: ToolsClient | undefined;

    constructor(options: VideogenApiClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get files(): FilesClient {
        return (this._files ??= new FilesClient(this._options));
    }

    public get webhooks(): WebhooksClient {
        return (this._webhooks ??= new WebhooksClient(this._options));
    }

    public get tools(): ToolsClient {
        return (this._tools ??= new ToolsClient(this._options));
    }
}
