// This file was auto-generated by Fern from our API Definition.

import { FilesClient } from "./api/resources/files/client/Client.js";
import { ProjectsClient } from "./api/resources/projects/client/Client.js";
import { ResourcesClient } from "./api/resources/resources/client/Client.js";
import { TextClient } from "./api/resources/text/client/Client.js";
import { ToolsClient } from "./api/resources/tools/client/Client.js";
import { WebhooksClient } from "./api/resources/webhooks/client/Client.js";
import { WorkflowsClient } from "./api/resources/workflows/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";
import * as core from "./core/index.js";

export declare namespace VideoGenClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class VideoGenClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<VideoGenClient.Options>;
    protected _workflows: WorkflowsClient | undefined;
    protected _projects: ProjectsClient | undefined;
    protected _tools: ToolsClient | undefined;
    protected _files: FilesClient | undefined;
    protected _text: TextClient | undefined;
    protected _resources: ResourcesClient | undefined;
    protected _webhooks: WebhooksClient | undefined;

    constructor(options: VideoGenClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get workflows(): WorkflowsClient {
        return (this._workflows ??= new WorkflowsClient(this._options));
    }

    public get projects(): ProjectsClient {
        return (this._projects ??= new ProjectsClient(this._options));
    }

    public get tools(): ToolsClient {
        return (this._tools ??= new ToolsClient(this._options));
    }

    public get files(): FilesClient {
        return (this._files ??= new FilesClient(this._options));
    }

    public get text(): TextClient {
        return (this._text ??= new TextClient(this._options));
    }

    public get resources(): ResourcesClient {
        return (this._resources ??= new ResourcesClient(this._options));
    }

    public get webhooks(): WebhooksClient {
        return (this._webhooks ??= new WebhooksClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
                getAuthHeaders: async () => (await this._options.authProvider.getAuthRequest()).headers,
            },
            requestOptions,
        );
    }
}
