// This file was auto-generated by Fern from our API Definition.

export const VideogenApiEnvironment = {
    Production: "https://api.videogen.io",
} as const;

export type VideogenApiEnvironment = typeof VideogenApiEnvironment.Production;
